import type { JourneyTrack } from "../backend/sonicJourney";
import type { JourneyChoice, useSonicJourney } from "./useSonicJourney";
import "./SonicJourneyPanel.css";
export function SonicJourneyPanel({ journey: j, currentTrack, onPlay }: { journey: ReturnType<typeof useSonicJourney>; currentTrack?: JourneyChoice; onPlay?: (tracks: JourneyTrack[]) => Promise<void> }) {
  const total = j.stops.length + Math.max(0, j.stops.length - 1) * j.connecting;
  return <section className="sonic-journey" aria-label="Sonic journey">
    <h3>Sonic journey</h3><p>Choose 2–10 tracks as ordered stops. Connect each pair through analyzed music with no repeated tracks.</p>
    {currentTrack && <button type="button" disabled={j.busy || j.stops.length >= 10 || j.stops.some(s => s.trackKey === currentTrack.trackKey)} onClick={() => j.add(currentTrack)}>Add selected track as stop</button>}
    <form onSubmit={e => { e.preventDefault(); void j.search(); }} className="journey-search"><label>Find analyzed tracks<input value={j.text} maxLength={200} disabled={j.busy} onChange={e => j.changeText(e.target.value)} placeholder="Artist or title" /></label><button type="submit" disabled={j.busy || j.text.trim().length < 2}>Search stops</button></form>
    {j.choices.length > 0 && <div className="journey-choices">{j.choices.map(t => <button type="button" key={t.trackKey} disabled={j.busy || j.stops.length >= 10 || j.stops.some(s => s.trackKey === t.trackKey)} onClick={() => j.add(t)} aria-label={`Add ${t.title}`}><strong>{t.title}</strong><span>{t.artist} · {t.album}</span></button>)}</div>}
    {j.searched && !j.choices.length && <p role="status">No current analyzed tracks match. Try another artist/title or analyze more music in Music Library.</p>}
    <ol className="journey-stops">{j.stops.map((s, i) => <li key={s.trackKey}><strong>{s.title}</strong><span>{s.artist}</span><div className="journey-actions"><button type="button" disabled={j.busy || i === 0} onClick={() => j.move(i, -1)} aria-label={`Move ${s.title} earlier`}>↑</button><button type="button" disabled={j.busy || i === j.stops.length - 1} onClick={() => j.move(i, 1)} aria-label={`Move ${s.title} later`}>↓</button><button type="button" disabled={j.busy} onClick={() => j.remove(i)} aria-label={`Remove ${s.title}`}>Remove</button></div></li>)}</ol>
    <div className="journey-controls"><label>Connecting tracks between stops<select value={j.connecting} disabled={j.busy} onChange={e => j.changeConnecting(Number(e.target.value))}>{Array.from({ length: 10 }, (_, i) => <option key={i + 1} value={i + 1}>{i + 1}</option>)}</select></label><label>Connector minimum rating<select value={j.rating ?? ""} disabled={j.busy} onChange={e => j.changeRating(e.target.value ? Number(e.target.value) : null)}><option value="">Any</option><option value="60">3 stars</option><option value="80">4 stars</option><option value="100">5 stars</option></select></label><label><input type="checkbox" checked={j.sameGenre} disabled={j.busy} onChange={e => j.changeGenre(e.target.checked)} />Connectors in first stop’s genre</label></div>
    <p>{j.stops.length} stops · {total} tracks including connectors</p><button type="button" disabled={j.busy || j.stops.length < 2} onClick={() => void j.build()}>{j.busy ? "Working…" : "Build sonic journey"}</button>
    {j.result && !j.result.complete && <p role="status">{j.result.stopsReady.some(ready => !ready) ? `Stops ${j.result.stopsReady.flatMap((ready, i) => ready ? [] : [i + 1]).join(", ")} need current audio analysis or are banned. Analyze them in Music Library first.` : "Not enough eligible connecting tracks for this journey. Try fewer connectors, change the filters, or analyze more music."}</p>}
    {j.result?.complete && <><p role="status">{j.result.tracks.length} tracks through {j.stops.length} stops · compared {j.result.analyzed.toLocaleString()} saved analyses. Keep this order for the journey.</p><ol className="journey-preview">{j.result.tracks.map(t => <li key={t.trackKey}><strong>{t.title}{j.stops.some(s => s.trackKey === t.trackKey) ? " · Stop" : ""}</strong><span>{t.artist} · {t.album}</span></li>)}</ol><label>Journey name<input value={j.name} maxLength={120} disabled={j.busy} onChange={e => j.setName(e.target.value)} /></label><div className="journey-actions"><button type="button" disabled={j.busy || !j.name.trim()} onClick={() => void j.save()}>Save journey playlist</button>{onPlay && <button type="button" disabled={j.busy} onClick={() => void j.run(() => onPlay(j.result!.tracks))}>Play journey</button>}</div></>}
    {j.message && <p role="status">{j.message}</p>}{j.error && <p role="alert">{j.error}</p>}
  </section>;
}
