import { act, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { SonicBackupPanel } from "./SonicBackupPanel";
import * as backend from "../backend/sonicBackup";
vi.mock("../backend/sonicBackup", () => ({ analysisBackupFolder: vi.fn(), chooseAnalysisBackup: vi.fn(), chooseAnalysisBackupFolder: vi.fn(), exportAnalysisBackup: vi.fn(), inspectAnalysisBackup: vi.fn(), restoreAnalysisBackup: vi.fn(), analysisBackupStatus: vi.fn(), configureAnalysisBackup: vi.fn() }));
beforeEach(() => vi.mocked(backend.analysisBackupStatus).mockResolvedValue({ schedule: { enabled: false, intervalHours: 6, backupsToKeep: 7, folder: "OneDrive/_musicbackup/sonic-analysis" }, lastBackup: null, nextBackupAt: null, lastError: null, running: false }));
afterEach(() => vi.resetAllMocks());
const archive: backend.AnalysisBackup = { path: "OneDrive/archive.sonic-backup", createdAt: "2026-10-08T12:00:00Z", archiveVersion: 1, profile: "test", dimensions: 23, audioCount: 12345, databaseBytes: 1024*1024, sha256: "reviewed-digest" };
it("preselects OneDrive and reviews the selected archive before a guarded merge", async () => {
  vi.mocked(backend.analysisBackupFolder).mockResolvedValue("OneDrive/_musicbackup/sonic-analysis");
  vi.mocked(backend.chooseAnalysisBackup).mockResolvedValue(archive.path);
  vi.mocked(backend.inspectAnalysisBackup).mockResolvedValue(archive);
  vi.mocked(backend.restoreAnalysisBackup).mockResolvedValue({ added: 12300, alreadyPresent: 45, safetyBackup: "local/safety.sonic-backup" });
  const verify = vi.fn().mockResolvedValue(undefined);
  render(<SonicBackupPanel onVerify={verify} />);
  fireEvent.click(screen.getByText("Backup and cross-PC reuse"));
  await screen.findByText(/Backup folder: OneDrive/);
  fireEvent.click(screen.getByText("Choose backup to restore"));
  await screen.findByText("12,345 reusable audio results");
  expect(backend.restoreAnalysisBackup).not.toHaveBeenCalled();
  fireEvent.click(screen.getByText("Merge this backup"));
  await waitFor(() => expect(backend.restoreAnalysisBackup).toHaveBeenCalledWith(archive));
  await screen.findByText(/Merged 12,300 audio results; 45 already present/);
  expect(verify).not.toHaveBeenCalled();
  fireEvent.click(screen.getByText("Verify reused analysis"));
  await waitFor(() => expect(verify).toHaveBeenCalledOnce());
});
it("invalid archives cannot be applied and a failed merge retains its review for retry", async () => {
  vi.mocked(backend.analysisBackupFolder).mockResolvedValue(null);
  vi.mocked(backend.chooseAnalysisBackup).mockResolvedValue(archive.path);
  vi.mocked(backend.inspectAnalysisBackup).mockRejectedValueOnce(new Error("Checksum mismatch")).mockResolvedValue(archive);
  vi.mocked(backend.restoreAnalysisBackup).mockRejectedValue(new Error("Pause audio analysis first"));
  render(<SonicBackupPanel onVerify={vi.fn()} />);
  fireEvent.click(screen.getByText("Backup and cross-PC reuse"));
  fireEvent.click(screen.getByText("Choose backup to restore"));
  expect(await screen.findByRole("alert")).toHaveTextContent("Checksum mismatch");
  expect(screen.queryByText("Merge this backup")).not.toBeInTheDocument();
  fireEvent.click(screen.getByText("Choose backup to restore"));
  fireEvent.click(await screen.findByText("Merge this backup"));
  expect(await screen.findByRole("alert")).toHaveTextContent("Pause audio analysis first");
  expect(screen.getByText("Merge this backup")).toBeEnabled();
});
it("holds controls while exporting and reports the separate OneDrive upload step", async () => {
  vi.mocked(backend.analysisBackupFolder).mockResolvedValue("OneDrive/_musicbackup/sonic-analysis");
  let finish!: (value: backend.AnalysisBackup) => void;
  vi.mocked(backend.exportAnalysisBackup).mockReturnValue(new Promise(resolve => { finish = resolve; }));
  render(<SonicBackupPanel onVerify={vi.fn()} />);
  fireEvent.click(screen.getByText("Backup and cross-PC reuse"));
  await waitFor(() => expect(screen.getByText("Back up analysis")).toBeEnabled());
  fireEvent.click(screen.getByText("Back up analysis"));
  expect(screen.getByText("Choose backup to restore")).toBeDisabled();
  await act(async () => finish(archive));
  expect(await screen.findByText(/Wait for OneDrive to finish uploading/)).toBeInTheDocument();
});
