//! Generated TypeScript bindings (tauri-specta).
//!
//! Commands listed in `specta_commands!` are dispatched by tauri-specta and
//! exported to `src/bindings.ts`. All other commands still go through
//! `tauri::generate_handler!` in `lib.rs`; `compose_invoke_handler` routes each
//! call by command name, so domains can migrate one at a time.

use std::path::Path;

use tauri::ipc::Invoke;
use tauri::Wry;
use tauri_specta::{Builder, ErrorHandlingMode};

use super::{
    search_library,
    list_artists,
    get_artist_track_highlights,
    list_genres,
    list_saved_searches,
    save_search,
    delete_saved_search,
    list_saved_charts,
    save_chart,
    delete_saved_chart,
    export_search,
    export_music_tool_issues,
    list_music_tools,
    list_music_tool_issues,
    fix_music_tool_issues,
    list_music_tool_fix_history,
    undo_music_tool_fix,
    get_statistics,
    list_library_updates,
    list_library_update_artists,
    get_album_debut_timeline,
    get_track_debut_timeline,
    get_music_map,
    get_music_map_location_details,
    refresh_music_map_locations,
    get_year_progress,
    get_genre_progress,
    get_discovery,
    get_discovery_daily_edition,
    get_discovery_source_health,
    rebuild_discovery_chart_matches,
    get_discovery_anniversaries,
    get_discovery_chart_snapshot,
    get_discovery_deep_cut_snapshot,
    get_discovery_completion_snapshot,
    get_discovery_recommendation_snapshot,
    get_discovery_mixer_seed_options,
    get_discovery_mixer,
    get_discovery_shelf_explorer,
    get_genre_timeline,
    get_artist_timeline,
    list_genre_suggestions,
    soulseek, usenet,
    get_artist_biography,
    get_album_review,
    score_mixtape_candidates,
    list_saved_external_discoveries,
    save_external_discovery,
    get_app_update_status,
    check_app_update,
    get_music_doctor_status,
    get_deemix_credential_status,
    save_deemix_arl,
    delete_deemix_arl,
    test_deemix_connection,
    search_deemix_albums,
    download_deemix_album,
    preflight_deemix_album_download,
    import_published_charts,
    get_published_chart_catalog,
    get_published_artist_rankings,
    get_published_song_rankings,
    get_published_song_history,
    list_published_chart_weeks,
    get_published_chart_entries,
    get_discogs_credential_status,
    save_discogs_credentials,
    delete_discogs_credentials,
    test_discogs_connection,
    get_lastfm_credential_status,
    save_lastfm_api_key,
    delete_lastfm_api_key,
    test_lastfm_connection,
    get_lastfm_artist_popularity,
    get_lastfm_artist_similarity,
    get_lastfm_artist_constellation_branch,
    get_lastfm_album_popularity,
    get_lastfm_related_albums,
    list_wish_list,
    add_wish_list_item,
    remove_wish_list_item,
    discover_wish_list_artist_albums,
    refresh_wish_list_artist_album_summary,
    get_library_completion,
    get_library_completion_verification_status,
    start_library_completion_verification,
    set_library_completion_verification_state,
    retry_library_completion_verification_failures,
    set_library_completion_decision,
    get_library_completion_artists,
    get_library_completion_artist_verification_status,
    start_library_completion_artist_verification,
    set_library_completion_artist_verification_state,
    retry_library_completion_artist_verification_failures,
    confirm_library_completion_artist_match,
    set_library_completion_artist_decision,
    enrich_library_completion_cover,
    get_ai_key_status,
    save_openai_api_key,
    delete_openai_api_key,
    test_openai_connection,
    compile_natural_language_query,
    ask_current_view,
    research_music,
    analyze_library,
    list_ai_snapshots,
    save_ai_snapshot,
    delete_ai_snapshot,
    build_playlist,
    get_jev_key_status,
    save_openrouter_api_key,
    delete_openrouter_api_key,
    test_jev_connection,
    export_ai_markdown,
    list_saved_playlists,
    save_playlist,
    delete_saved_playlist,
    set_playlist_automation,
    refresh_smart_playlist,
    discover_outside_library,
    export_playlist
};

macro_rules! specta_commands {
    ($($b:ident $(:: $p:ident)*),* $(,)?) => {
        (
            tauri_specta::collect_commands![$($b $(:: $p)*),*],
            // Command names are the last path segment, as Tauri invokes them.
            vec![$(last_segment(stringify!($b $(:: $p)*))),*],
        )
    };
}

fn last_segment(path: &'static str) -> &'static str {
    path.rsplit("::").next().unwrap_or(path).trim()
}

fn builder() -> (Builder<Wry>, Vec<&'static str>) {
    let (commands, names) = specta_commands![
        search_library,
        list_artists,
        get_artist_track_highlights,
        list_genres,
        list_saved_searches,
        save_search,
        delete_saved_search,
        list_saved_charts,
        save_chart,
        delete_saved_chart,
        export_search,
        export_music_tool_issues,
        list_music_tools,
        list_music_tool_issues,
        fix_music_tool_issues,
        list_music_tool_fix_history,
        undo_music_tool_fix,
        get_statistics,
        list_library_updates,
        list_library_update_artists,
        get_album_debut_timeline,
        get_track_debut_timeline,
        get_music_map,
        get_music_map_location_details,
        refresh_music_map_locations,
        get_year_progress,
        get_genre_progress,
        get_discovery,
        get_discovery_daily_edition,
        get_discovery_source_health,
        rebuild_discovery_chart_matches,
        get_discovery_anniversaries,
        get_discovery_chart_snapshot,
        get_discovery_deep_cut_snapshot,
        get_discovery_completion_snapshot,
        get_discovery_recommendation_snapshot,
        get_discovery_mixer_seed_options,
        get_discovery_mixer,
        get_discovery_shelf_explorer,
        get_genre_timeline,
        get_artist_timeline,
        list_genre_suggestions,
        usenet::usenet_bootstrap,
        usenet::usenet_save_profile,
        usenet::usenet_reset,
        usenet::usenet_test_connections,
        usenet::usenet_search,
        usenet::usenet_transfers_snapshot,
        usenet::usenet_enqueue_download,
        usenet::usenet_clear_completed,
        soulseek::local_shares_snapshot,
        soulseek::local_shares_add,
        soulseek::local_shares_remove,
        soulseek::local_shares_set_enabled,
        soulseek::local_shares_rescan,
        soulseek::local_shares_set_upload_slots,
        soulseek::uploads_snapshot,
        soulseek::upload_cancel,
        soulseek::upload_clear_finished,
        soulseek::transfers_snapshot,
        soulseek::transfer_set_max_concurrent_downloads,
        soulseek::transfer_enqueue_release,
        soulseek::transfer_pause_release,
        soulseek::transfer_resume_release,
        soulseek::transfer_cancel_release,
        soulseek::transfer_clear_completed,
        soulseek::transfer_reveal_release_path,
        soulseek::connection_bootstrap,
        soulseek::connection_save_profile,
        soulseek::connection_connect,
        soulseek::connection_disconnect,
        soulseek::connection_reset,
        soulseek::search_snapshot,
        soulseek::search_start,
        soulseek::search_stop,
        soulseek::search_close,
        get_artist_biography,
        get_album_review,
        score_mixtape_candidates,
        list_saved_external_discoveries,
        save_external_discovery,
        get_app_update_status,
        check_app_update,
        get_music_doctor_status,
        get_deemix_credential_status,
        save_deemix_arl,
        delete_deemix_arl,
        test_deemix_connection,
        search_deemix_albums,
        download_deemix_album,
        preflight_deemix_album_download,
        import_published_charts,
        get_published_chart_catalog,
        get_published_artist_rankings,
        get_published_song_rankings,
        get_published_song_history,
        list_published_chart_weeks,
        get_published_chart_entries,
        get_discogs_credential_status,
        save_discogs_credentials,
        delete_discogs_credentials,
        test_discogs_connection,
        get_lastfm_credential_status,
        save_lastfm_api_key,
        delete_lastfm_api_key,
        test_lastfm_connection,
        get_lastfm_artist_popularity,
        get_lastfm_artist_similarity,
        get_lastfm_artist_constellation_branch,
        get_lastfm_album_popularity,
        get_lastfm_related_albums,
        list_wish_list,
        add_wish_list_item,
        remove_wish_list_item,
        discover_wish_list_artist_albums,
        refresh_wish_list_artist_album_summary,
        get_library_completion,
        get_library_completion_verification_status,
        start_library_completion_verification,
        set_library_completion_verification_state,
        retry_library_completion_verification_failures,
        set_library_completion_decision,
        get_library_completion_artists,
        get_library_completion_artist_verification_status,
        start_library_completion_artist_verification,
        set_library_completion_artist_verification_state,
        retry_library_completion_artist_verification_failures,
        confirm_library_completion_artist_match,
        set_library_completion_artist_decision,
        enrich_library_completion_cover,
        get_ai_key_status,
        save_openai_api_key,
        delete_openai_api_key,
        test_openai_connection,
        compile_natural_language_query,
        ask_current_view,
        research_music,
        analyze_library,
        list_ai_snapshots,
        save_ai_snapshot,
        delete_ai_snapshot,
        build_playlist,
        get_jev_key_status,
        save_openrouter_api_key,
        delete_openrouter_api_key,
        test_jev_connection,
        export_ai_markdown,
        list_saved_playlists,
        save_playlist,
        delete_saved_playlist,
        set_playlist_automation,
        refresh_smart_playlist,
        discover_outside_library,
        export_playlist
    ];
    (
        Builder::<Wry>::new()
            .commands(commands)
            // Keep the existing contract: command errors reject the promise.
            .error_handling(ErrorHandlingMode::Throw)
            // Row ids and counts stay far below 2^53, as with the hand-written types.
            .dangerously_cast_bigints_to_number(),
        names,
    )
}

pub fn export(path: &Path) -> Result<(), String> {
    let (builder, _) = builder();
    builder
        .export(specta_typescript::Typescript::default(), path)
        .map_err(|error| error.to_string())
}

/// Routes migrated commands to tauri-specta and everything else to `legacy`.
pub fn compose_invoke_handler(
    legacy: impl Fn(Invoke<Wry>) -> bool + Send + Sync + 'static,
) -> impl Fn(Invoke<Wry>) -> bool + Send + Sync + 'static {
    let (builder, names) = builder();
    // The handler borrows the builder; it lives for the whole process anyway.
    let builder: &'static Builder<Wry> = Box::leak(Box::new(builder));
    let migrated = builder.invoke_handler();
    move |invoke| {
        if names.contains(&invoke.message.command()) {
            migrated(invoke)
        } else {
            legacy(invoke)
        }
    }
}
