//! Generated TypeScript bindings (tauri-specta).
//!
//! Every Tauri command is listed once in `specta_commands!`. tauri-specta both
//! dispatches the calls and exports their types to `src/bindings.ts`, so a
//! command cannot exist without a generated TypeScript signature.

use std::path::Path;

use tauri::ipc::Invoke;
use tauri::Wry;
use tauri_specta::{Builder, ErrorHandlingMode};

use super::{
    sonic,
    sonic_backup,
    sonic_backup_schedule,
    acknowledge_catalog_revision,
    refresh_lastfm_artist_images,
    search_wish_list_musicbrainz,
    add_wish_list_musicbrainz_candidate,
    import_musicbrainz_origin_countries,
    import_musicbrainz_artist_infos,
    sync_musicbrainz_overlay,
    sync_music_doctor,
    import_album_covers,
    get_library_status,
    run_performance_probe,
    list_import_runs,
    get_catalog_revision,
    list_database_backups,
    restore_database_backup,
    get_settings,
    delete_saved_external_discovery,
    get_musicbrainz_cache_status,
    get_musicbrainz_origin_country_status,
    preview_musicbrainz_origin_country_import,
    cancel_musicbrainz_origin_country_import,
    get_musicbrainz_artist_info_status,
    preview_musicbrainz_artist_info_import,
    cancel_musicbrainz_artist_info_import,
    get_musicbrainz_artist_discography,
    set_musicbrainz_release_decision,
    set_musicbrainz_artist_link,
    refresh_musicbrainz_artist_releases,
    set_musicbrainz_artist_origin_country,
    list_musicbrainz_overlay_sync_log,
    save_settings,
    install_app_update,
    export_musicbrainz_artist_releases,
    get_import_preview,
    prepare_import_preview,
    cancel_import_preview,
    apply_import_preview,
    rollback_import_run,
    import_billboard_charts,
    import_billboard_singles,
    import_vg_lista_albums,
    import_vg_lista_singles,
    import_official_uk_albums,
    import_official_uk_singles,
    import_ti_i_skuddet_singles,
    import_norsktoppen_singles,
    list_activity_jobs,
    control_activity_job,
    search_library,
    list_artists,
    get_artist_track_highlights,
    list_genres,
    list_saved_searches,
    save_search,
    delete_saved_search,
    list_saved_charts,
    save_chart,
    delete_saved_chart,
    export_search,
    export_music_tool_issues,
    list_music_tools,
    list_music_tool_issues,
    fix_music_tool_issues,
    list_music_tool_fix_history,
    undo_music_tool_fix,
    get_statistics,
    list_library_updates,
    list_library_update_artists,
    get_album_debut_timeline,
    get_track_debut_timeline,
    get_music_map,
    get_music_map_location_details,
    refresh_music_map_locations,
    get_year_progress,
    get_genre_progress,
    get_discovery,
    get_discovery_daily_edition,
    get_discovery_source_health,
    rebuild_discovery_chart_matches,
    get_discovery_anniversaries,
    get_discovery_chart_snapshot,
    get_discovery_deep_cut_snapshot,
    get_discovery_completion_snapshot,
    get_discovery_recommendation_snapshot,
    get_discovery_mixer_seed_options,
    get_discovery_mixer,
    get_discovery_shelf_explorer,
    get_genre_timeline,
    get_artist_timeline,
    list_genre_suggestions,
    soulseek, usenet,
    get_artist_biography,
    get_album_review,
    score_mixtape_candidates,
    list_saved_external_discoveries,
    save_external_discovery,
    get_app_update_status,
    check_app_update,
    get_music_doctor_status,
    get_deemix_credential_status,
    save_deemix_arl,
    delete_deemix_arl,
    test_deemix_connection,
    search_deemix_albums,
    download_deemix_album,
    preflight_deemix_album_download,
    import_published_charts,
    get_published_chart_catalog,
    get_published_artist_rankings,
    get_published_song_rankings,
    get_published_song_history,
    list_published_chart_weeks,
    get_published_chart_entries,
    get_discogs_credential_status,
    save_discogs_credentials,
    delete_discogs_credentials,
    test_discogs_connection,
    get_lastfm_credential_status,
    save_lastfm_api_key,
    delete_lastfm_api_key,
    test_lastfm_connection,
    get_lastfm_artist_popularity,
    get_lastfm_artist_similarity,
    get_lastfm_artist_constellation_branch,
    get_lastfm_album_popularity,
    get_lastfm_related_albums,
    list_wish_list,
    add_wish_list_item,
    remove_wish_list_item,
    discover_wish_list_artist_albums,
    refresh_wish_list_artist_album_summary,
    get_library_completion,
    get_library_completion_verification_status,
    start_library_completion_verification,
    set_library_completion_verification_state,
    retry_library_completion_verification_failures,
    set_library_completion_decision,
    get_library_completion_artists,
    get_library_completion_artist_verification_status,
    start_library_completion_artist_verification,
    set_library_completion_artist_verification_state,
    retry_library_completion_artist_verification_failures,
    confirm_library_completion_artist_match,
    set_library_completion_artist_decision,
    enrich_library_completion_cover,
    get_ai_key_status,
    save_openai_api_key,
    delete_openai_api_key,
    test_openai_connection,
    compile_natural_language_query,
    ask_current_view,
    research_music,
    analyze_library,
    list_ai_snapshots,
    save_ai_snapshot,
    delete_ai_snapshot,
    build_playlist,
    get_jev_key_status,
    save_openrouter_api_key,
    delete_openrouter_api_key,
    test_jev_connection,
    export_ai_markdown,
    list_saved_playlists,
    save_playlist,
    delete_saved_playlist,
    set_playlist_automation,
    refresh_smart_playlist,
    discover_outside_library,
    export_playlist
};

macro_rules! specta_commands {
    ($($b:ident $(:: $p:ident)*),* $(,)?) => {
        tauri_specta::collect_commands![$($b $(:: $p)*),*]
    };
}

fn builder() -> Builder<Wry> {
    let commands = specta_commands![
        sonic::sonic_status,
        sonic_backup::sonic_backup_folder,
        sonic_backup::sonic_backup_export,
        sonic_backup::sonic_backup_inspect,
        sonic_backup::sonic_backup_restore,
        sonic_backup_schedule::sonic_backup_status,
        sonic_backup_schedule::sonic_backup_configure,
        sonic::sonic_configure,
        sonic::sonic_seeds,
        sonic::sonic_journey,
        sonic::sonic_journey_search,
        sonic::sonic_save_journey,
        sonic::sonic_matches,
        sonic::sonic_album_matches,
        sonic::sonic_analyze,
        sonic::sonic_save_playlist,
        acknowledge_catalog_revision,
        refresh_lastfm_artist_images,
        search_wish_list_musicbrainz,
        add_wish_list_musicbrainz_candidate,
        import_musicbrainz_origin_countries,
        import_musicbrainz_artist_infos,
        sync_musicbrainz_overlay,
        sync_music_doctor,
        import_album_covers,
        get_library_status,
        run_performance_probe,
        list_import_runs,
        get_catalog_revision,
        list_database_backups,
        restore_database_backup,
        get_settings,
        delete_saved_external_discovery,
        get_musicbrainz_cache_status,
        get_musicbrainz_origin_country_status,
        preview_musicbrainz_origin_country_import,
        cancel_musicbrainz_origin_country_import,
        get_musicbrainz_artist_info_status,
        preview_musicbrainz_artist_info_import,
        cancel_musicbrainz_artist_info_import,
        get_musicbrainz_artist_discography,
        set_musicbrainz_release_decision,
        set_musicbrainz_artist_link,
        refresh_musicbrainz_artist_releases,
        set_musicbrainz_artist_origin_country,
        list_musicbrainz_overlay_sync_log,
        save_settings,
        install_app_update,
        export_musicbrainz_artist_releases,
        get_import_preview,
        prepare_import_preview,
        cancel_import_preview,
        apply_import_preview,
        rollback_import_run,
        import_billboard_charts,
        import_billboard_singles,
        import_vg_lista_albums,
        import_vg_lista_singles,
        import_official_uk_albums,
        import_official_uk_singles,
        import_ti_i_skuddet_singles,
        import_norsktoppen_singles,
        list_activity_jobs,
        control_activity_job,
        search_library,
        list_artists,
        get_artist_track_highlights,
        list_genres,
        list_saved_searches,
        save_search,
        delete_saved_search,
        list_saved_charts,
        save_chart,
        delete_saved_chart,
        export_search,
        export_music_tool_issues,
        list_music_tools,
        list_music_tool_issues,
        fix_music_tool_issues,
        list_music_tool_fix_history,
        undo_music_tool_fix,
        get_statistics,
        list_library_updates,
        list_library_update_artists,
        get_album_debut_timeline,
        get_track_debut_timeline,
        get_music_map,
        get_music_map_location_details,
        refresh_music_map_locations,
        get_year_progress,
        get_genre_progress,
        get_discovery,
        get_discovery_daily_edition,
        get_discovery_source_health,
        rebuild_discovery_chart_matches,
        get_discovery_anniversaries,
        get_discovery_chart_snapshot,
        get_discovery_deep_cut_snapshot,
        get_discovery_completion_snapshot,
        get_discovery_recommendation_snapshot,
        get_discovery_mixer_seed_options,
        get_discovery_mixer,
        get_discovery_shelf_explorer,
        get_genre_timeline,
        get_artist_timeline,
        list_genre_suggestions,
        usenet::usenet_bootstrap,
        usenet::usenet_save_profile,
        usenet::usenet_reset,
        usenet::usenet_test_connections,
        usenet::usenet_search,
        usenet::usenet_transfers_snapshot,
        usenet::usenet_enqueue_download,
        usenet::usenet_clear_completed,
        soulseek::local_shares_snapshot,
        soulseek::local_shares_add,
        soulseek::local_shares_remove,
        soulseek::local_shares_set_enabled,
        soulseek::local_shares_rescan,
        soulseek::local_shares_set_upload_slots,
        soulseek::uploads_snapshot,
        soulseek::upload_cancel,
        soulseek::upload_clear_finished,
        soulseek::transfers_snapshot,
        soulseek::transfer_set_max_concurrent_downloads,
        soulseek::transfer_enqueue_release,
        soulseek::transfer_pause_release,
        soulseek::transfer_resume_release,
        soulseek::transfer_cancel_release,
        soulseek::transfer_clear_completed,
        soulseek::transfer_reveal_release_path,
        soulseek::connection_bootstrap,
        soulseek::connection_save_profile,
        soulseek::connection_connect,
        soulseek::connection_disconnect,
        soulseek::connection_reset,
        soulseek::search_snapshot,
        soulseek::search_start,
        soulseek::search_stop,
        soulseek::search_close,
        get_artist_biography,
        get_album_review,
        score_mixtape_candidates,
        list_saved_external_discoveries,
        save_external_discovery,
        get_app_update_status,
        check_app_update,
        get_music_doctor_status,
        get_deemix_credential_status,
        save_deemix_arl,
        delete_deemix_arl,
        test_deemix_connection,
        search_deemix_albums,
        download_deemix_album,
        preflight_deemix_album_download,
        import_published_charts,
        get_published_chart_catalog,
        get_published_artist_rankings,
        get_published_song_rankings,
        get_published_song_history,
        list_published_chart_weeks,
        get_published_chart_entries,
        get_discogs_credential_status,
        save_discogs_credentials,
        delete_discogs_credentials,
        test_discogs_connection,
        get_lastfm_credential_status,
        save_lastfm_api_key,
        delete_lastfm_api_key,
        test_lastfm_connection,
        get_lastfm_artist_popularity,
        get_lastfm_artist_similarity,
        get_lastfm_artist_constellation_branch,
        get_lastfm_album_popularity,
        get_lastfm_related_albums,
        list_wish_list,
        add_wish_list_item,
        remove_wish_list_item,
        discover_wish_list_artist_albums,
        refresh_wish_list_artist_album_summary,
        get_library_completion,
        get_library_completion_verification_status,
        start_library_completion_verification,
        set_library_completion_verification_state,
        retry_library_completion_verification_failures,
        set_library_completion_decision,
        get_library_completion_artists,
        get_library_completion_artist_verification_status,
        start_library_completion_artist_verification,
        set_library_completion_artist_verification_state,
        retry_library_completion_artist_verification_failures,
        confirm_library_completion_artist_match,
        set_library_completion_artist_decision,
        enrich_library_completion_cover,
        get_ai_key_status,
        save_openai_api_key,
        delete_openai_api_key,
        test_openai_connection,
        compile_natural_language_query,
        ask_current_view,
        research_music,
        analyze_library,
        list_ai_snapshots,
        save_ai_snapshot,
        delete_ai_snapshot,
        build_playlist,
        get_jev_key_status,
        save_openrouter_api_key,
        delete_openrouter_api_key,
        test_jev_connection,
        export_ai_markdown,
        list_saved_playlists,
        save_playlist,
        delete_saved_playlist,
        set_playlist_automation,
        refresh_smart_playlist,
        discover_outside_library,
        export_playlist
    ];
    Builder::<Wry>::new()
        .commands(commands)
        // Keep the existing contract: command errors reject the promise.
        .events(crate::events::collect())
        .error_handling(ErrorHandlingMode::Throw)
        // Row ids and counts stay far below 2^53, as with the hand-written types.
        .dangerously_cast_bigints_to_number()
}

pub fn export(path: &Path) -> Result<(), String> {
    builder()
        .export(specta_typescript::Typescript::default(), path)
        .map_err(|error| error.to_string())
}

/// Regenerates the bindings in debug builds so `tauri dev` always serves types that
/// match the Rust commands. The file is only rewritten when its content changed
/// (ignoring line endings), so the dev server does not reload for nothing.
#[cfg(debug_assertions)]
pub fn export_in_debug(path: &Path) {
    let temporary = std::env::temp_dir().join("music-library-bindings-dev.ts");
    let result = export(&temporary).and_then(|()| {
        let generated = std::fs::read_to_string(&temporary).map_err(|error| error.to_string())?;
        let current = std::fs::read_to_string(path).unwrap_or_default();
        let normalize = |text: &str| text.replace("
", "
");
        if normalize(&generated) != normalize(&current) {
            std::fs::write(path, generated).map_err(|error| error.to_string())?;
        }
        Ok(())
    });
    if let Err(error) = result {
        eprintln!("Could not refresh {}: {error}", path.display());
    }
}

/// The one builder shared by the invoke handler and event mounting. It lives for the
/// whole process, which also lets the handler borrow it as `'static`.
fn shared() -> &'static Builder<Wry> {
    static BUILDER: std::sync::OnceLock<Builder<Wry>> = std::sync::OnceLock::new();
    BUILDER.get_or_init(builder)
}

/// The Tauri invoke handler for every command.
pub fn invoke_handler() -> impl Fn(Invoke<Wry>) -> bool + Send + Sync + 'static {
    shared().invoke_handler()
}

/// Registers the typed events. Must run in `setup`, before anything emits one.
pub fn mount_events(app: &tauri::App) {
    shared().mount_events(app);
}
