// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getAiKeyStatus: () => __TAURI_INVOKE<AiKeyStatus>("get_ai_key_status"),
	saveOpenaiApiKey: (apiKey: string) => __TAURI_INVOKE<AiKeyStatus>("save_openai_api_key", { apiKey }),
	deleteOpenaiApiKey: () => __TAURI_INVOKE<AiKeyStatus>("delete_openai_api_key"),
	testOpenaiConnection: () => __TAURI_INVOKE<AiConnectionTest>("test_openai_connection"),
	compileNaturalLanguageQuery: (input: AiCompileRequest) => __TAURI_INVOKE<AiCompiledQuery_Serialize>("compile_natural_language_query", { input }),
	askCurrentView: (input: AiCurrentViewQuestion) => __TAURI_INVOKE<AiCurrentViewAnswer>("ask_current_view", { input }),
	researchMusic: (input: AiMusicResearchRequest) => __TAURI_INVOKE<AiMusicResearchAnswer>("research_music", { input }),
	analyzeLibrary: (input: AiLibraryAnalysisRequest) => __TAURI_INVOKE<AiLibraryAnalysis>("analyze_library", { input }),
	listAiSnapshots: (kind: string | null) => __TAURI_INVOKE<AiSnapshot_Serialize[]>("list_ai_snapshots", { kind }),
	saveAiSnapshot: (input: SaveAiSnapshotRequest_Deserialize) => __TAURI_INVOKE<AiSnapshot_Serialize>("save_ai_snapshot", { input }),
	deleteAiSnapshot: (id: number) => __TAURI_INVOKE<null>("delete_ai_snapshot", { id }),
	buildPlaylist: (input: AiPlaylistBuildRequest) => __TAURI_INVOKE<AiPlaylist_Serialize>("build_playlist", { input }),
	getJevKeyStatus: () => __TAURI_INVOKE<AiKeyStatus>("get_jev_key_status"),
	saveOpenrouterApiKey: (apiKey: string) => __TAURI_INVOKE<AiKeyStatus>("save_openrouter_api_key", { apiKey }),
	deleteOpenrouterApiKey: () => __TAURI_INVOKE<AiKeyStatus>("delete_openrouter_api_key"),
	testJevConnection: () => __TAURI_INVOKE<AiConnectionTest>("test_jev_connection"),
	exportAiMarkdown: (input: AiMarkdownExportRequest) => __TAURI_INVOKE<ExportResult>("export_ai_markdown", { input }),
	listSavedPlaylists: () => __TAURI_INVOKE<SavedPlaylist_Serialize[]>("list_saved_playlists"),
	savePlaylist: (input: SavePlaylistRequest_Deserialize) => __TAURI_INVOKE<SavedPlaylist_Serialize>("save_playlist", { input }),
	deleteSavedPlaylist: (id: number) => __TAURI_INVOKE<null>("delete_saved_playlist", { id }),
	setPlaylistAutomation: (input: SetPlaylistAutomationRequest) => __TAURI_INVOKE<SavedPlaylist_Serialize>("set_playlist_automation", { input }),
	refreshSmartPlaylist: (id: number) => __TAURI_INVOKE<SmartPlaylistRefreshResult_Serialize>("refresh_smart_playlist", { id }),
	discoverOutsideLibrary: (input: AiExternalDiscoveryRequest) => __TAURI_INVOKE<ExternalDiscoveryResponse>("discover_outside_library", { input }),
	exportPlaylist: (input: ExportPlaylistRequest_Deserialize) => __TAURI_INVOKE<ExportResult>("export_playlist", { input }),
};

/* Types */
export type AiCompileRequest = {
	prompt: string,
	target: string,
	currentView?: string | null,
	followUp?: AiQueryFollowUpContext | null,
};

export type AiCompiledQuery = AiCompiledQuery_Serialize | AiCompiledQuery_Deserialize;

export type AiCompiledQuery_Deserialize = {
	target: string,
	queryIntent?: string,
	summary: string,
	request: BrowseRequest,
	chartConfig: ChartConfig_Deserialize | null,
	model: string,
	usage: AiUsage,
};

export type AiCompiledQuery_Serialize = {
	target: string,
	queryIntent: string,
	summary: string,
	request: BrowseRequest,
	chartConfig: ChartConfig_Serialize | null,
	model: string,
	usage: AiUsage,
};

export type AiConnectionTest = {
	model: string,
	message: string,
	usage: AiUsage,
};

export type AiCurrentViewAnswer = {
	answer: string,
	view: string,
	matchingRows: number,
	analysisCount: number,
	namedRowsShared: number,
	model: string,
	usage: AiUsage,
};

export type AiCurrentViewQuestion = {
	question: string,
	request: BrowseRequest,
	scopeLabel?: string | null,
	scopeToResultLimit?: boolean,
};

export type AiExternalDiscoveryPlan = {
	prompt: string,
	entity: string,
	count: number,
	year: number,
	yearFrom?: number,
	yearTo?: number,
	yearMeaning: string,
	genres: string[],
	countries: string[],
	keywords: string,
	title: string,
	summary: string,
	model: string,
	usage: AiUsage,
};

export type AiExternalDiscoveryRequest = {
	prompt: string,
};

export type AiKeyStatus = {
	configured: boolean,
	source: string,
	model: string,
};

export type AiLibraryAnalysis = {
	lens: string,
	headline: string,
	summary: string,
	findings: AiLibraryFinding[],
	nextQuestions: string[],
	profileSections: string[],
	aggregatePointsShared: number,
	model: string,
	usage: AiUsage,
};

export type AiLibraryAnalysisRequest = {
	lens: string,
	focus?: string,
};

export type AiLibraryFinding = {
	title: string,
	evidence: string,
	interpretation: string,
};

export type AiMarkdownExportRequest = {
	title: string,
	markdown: string,
};

export type AiMusicResearchAnswer = {
	answer: string,
	sources: AiMusicResearchSource[],
	model: string,
	usage: AiUsage,
	usedWebSearch: boolean,
	localInspectionCount: number,
};

export type AiMusicResearchContext = {
	workspace: string,
	selectedEntityType?: string | null,
	selectedEntityId?: string | null,
	selectedLabel?: string | null,
	selectedSubtitle?: string | null,
};

export type AiMusicResearchExchange = {
	question: string,
	result: AiMusicResearchAnswer,
};

export type AiMusicResearchRequest = {
	question: string,
	context: AiMusicResearchContext,
	conversation?: AiMusicResearchTurn[],
};

export type AiMusicResearchSource = {
	title: string,
	url: string,
};

export type AiMusicResearchTurn = {
	role: string,
	content: string,
};

export type AiPlaylist = AiPlaylist_Serialize | AiPlaylist_Deserialize;

export type AiPlaylistBuildRequest = {
	prompt: string,
	sourceRequest?: BrowseRequest | null,
};

export type AiPlaylistTrack = {
	trackId: number,
	albumId: string,
	album: string | null,
	albumArtist: string | null,
	displayArtist: string | null,
	title: string | null,
	genre: string | null,
	year: number | null,
	seconds: number,
	rating: number | null,
	loved: boolean,
	filePath: string | null,
	filename: string | null,
};

export type AiPlaylist_Deserialize = {
	mixtape?: MixtapeDraft | null,
	prompt: string,
	name: string,
	description: string,
	request: BrowseRequest,
	strategy: string,
	targetTrackCount: number,
	targetMinutes: number,
	maxTracksPerArtist: number,
	maxTracksPerAlbum: number,
	matchingTrackCount: number,
	candidateCount: number,
	totalSeconds: number,
	tracks: AiPlaylistTrack[],
	model: string,
	usage: AiUsage,
};

export type AiPlaylist_Serialize = {
	mixtape?: MixtapeDraft | null,
	prompt: string,
	name: string,
	description: string,
	request: BrowseRequest,
	strategy: string,
	targetTrackCount: number,
	targetMinutes: number,
	maxTracksPerArtist: number,
	maxTracksPerAlbum: number,
	matchingTrackCount: number,
	candidateCount: number,
	totalSeconds: number,
	tracks: AiPlaylistTrack[],
	model: string,
	usage: AiUsage,
};

export type AiQueryExchange = AiQueryExchange_Serialize | AiQueryExchange_Deserialize;

export type AiQueryExchange_Deserialize = {
	prompt: string,
	result: AiCompiledQuery_Deserialize,
	answer?: AiCurrentViewAnswer | null,
};

export type AiQueryExchange_Serialize = {
	prompt: string,
	result: AiCompiledQuery_Serialize,
	answer: AiCurrentViewAnswer | null,
};

export type AiQueryFollowUpContext = {
	previousPrompt: string,
	previousSummary: string,
	previousAnswer: string,
};

export type AiSnapshot = AiSnapshot_Serialize | AiSnapshot_Deserialize;

export type AiSnapshotContent = AiSnapshotContent_Serialize | AiSnapshotContent_Deserialize;

export type AiSnapshotContent_Deserialize = ({ kind: "search"; prompt: string; result: AiCompiledQuery_Deserialize; answer?: AiCurrentViewAnswer | null; exchanges?: AiQueryExchange_Deserialize[] }) & { context?: never; request?: never } | ({ kind: "chart"; prompt: string; result: AiCompiledQuery_Deserialize; answer?: AiCurrentViewAnswer | null; exchanges?: AiQueryExchange_Deserialize[] }) & { context?: never; request?: never } | ({ kind: "searchAnswer"; prompt: string; request: BrowseRequest; result: AiCurrentViewAnswer }) & { answer?: never; context?: never; exchanges?: never } | ({ kind: "chartAnswer"; prompt: string; request: BrowseRequest; result: AiCurrentViewAnswer }) & { answer?: never; context?: never; exchanges?: never } | ({ kind: "libraryAnalysis"; prompt: string; result: AiLibraryAnalysis }) & { answer?: never; context?: never; exchanges?: never; request?: never } | ({ kind: "musicResearch"; prompt: string; context: AiMusicResearchContext; exchanges: AiMusicResearchExchange[] }) & { answer?: never; request?: never; result?: never };

export type AiSnapshotContent_Serialize = ({ kind: "search"; prompt: string; result: AiCompiledQuery_Serialize; answer: AiCurrentViewAnswer | null; exchanges: AiQueryExchange_Serialize[] }) & { context?: never; request?: never } | ({ kind: "chart"; prompt: string; result: AiCompiledQuery_Serialize; answer: AiCurrentViewAnswer | null; exchanges: AiQueryExchange_Serialize[] }) & { context?: never; request?: never } | ({ kind: "searchAnswer"; prompt: string; request: BrowseRequest; result: AiCurrentViewAnswer }) & { answer?: never; context?: never; exchanges?: never } | ({ kind: "chartAnswer"; prompt: string; request: BrowseRequest; result: AiCurrentViewAnswer }) & { answer?: never; context?: never; exchanges?: never } | ({ kind: "libraryAnalysis"; prompt: string; result: AiLibraryAnalysis }) & { answer?: never; context?: never; exchanges?: never; request?: never } | ({ kind: "musicResearch"; prompt: string; context: AiMusicResearchContext; exchanges: AiMusicResearchExchange[] }) & { answer?: never; request?: never; result?: never };

export type AiSnapshot_Deserialize = {
	id: number,
	title: string,
	content: AiSnapshotContent_Deserialize,
	libraryImportRunId: number | null,
	libraryImportedAt: string | null,
	libraryAlbumCount: number,
	libraryTrackCount: number,
	createdAt: string,
};

export type AiSnapshot_Serialize = {
	id: number,
	title: string,
	content: AiSnapshotContent_Serialize,
	libraryImportRunId: number | null,
	libraryImportedAt: string | null,
	libraryAlbumCount: number,
	libraryTrackCount: number,
	createdAt: string,
};

export type AiUsage = {
	inputTokens: number | null,
	cachedInputTokens: number | null,
	outputTokens: number | null,
};

export type Assessment = {
	trackId: number,
	sideA: Score,
	sideB: Score,
	opener: Score,
	builder: Score,
	breather: Score,
	closer: Score,
};

export type BrowseFilters = {
	albumIds?: string[],
	trackIds?: number[],
	artistKeys?: string[],
	albumTitle?: TextFilter,
	trackTitle?: TextFilter,
	albumArtist?: TextFilter,
	displayArtist?: TextFilter,
	publisher?: TextFilter,
	filePath?: TextFilter,
	filename?: TextFilter,
	hasTrackText?: string,
	genres?: string[],
	excludedGenres?: string[],
	missingFields?: string[],
	billboardRankMin?: number | null,
	billboardRankMax?: number | null,
	billboardSingleRankMin?: number | null,
	billboardSingleRankMax?: number | null,
	billboardSingleDebutDateFrom?: string | null,
	billboardSingleDebutDateTo?: string | null,
	billboardDebutWeekFrom?: string | null,
	billboardDebutWeekTo?: string | null,
	vgListaRankMin?: number | null,
	vgListaRankMax?: number | null,
	vgListaDebutWeekFrom?: string | null,
	vgListaDebutWeekTo?: string | null,
	officialUkRankMin?: number | null,
	officialUkRankMax?: number | null,
	officialUkDebutWeekFrom?: string | null,
	officialUkDebutWeekTo?: string | null,
	tiISkuddetRankMin?: number | null,
	tiISkuddetRankMax?: number | null,
	tiISkuddetDebutWeekFrom?: string | null,
	tiISkuddetDebutWeekTo?: string | null,
	norsktoppenRankMin?: number | null,
	norsktoppenRankMax?: number | null,
	norsktoppenDebutWeekFrom?: string | null,
	norsktoppenDebutWeekTo?: string | null,
	yearFrom?: number | null,
	yearTo?: number | null,
	releaseYearFrom?: number | null,
	releaseYearTo?: number | null,
	totalMinutesMin?: number | null,
	totalMinutesMax?: number | null,
	trackCountMin?: number | null,
	trackCountMax?: number | null,
	ratedTracksMin?: number | null,
	ratedTracksMax?: number | null,
	albumRatingMin?: number | null,
	albumRatingMax?: number | null,
	trackRatingMin?: number | null,
	trackRatingMax?: number | null,
	ratingCompletenessMin?: number | null,
	ratingCompletenessMax?: number | null,
	notFullyRated?: boolean,
	lovedTracksMin?: number | null,
	lovedTracksMax?: number | null,
	bitrateKbpsMin?: number | null,
	bitrateKbpsMax?: number | null,
	mixedAudioQuality?: boolean,
	originCountryCodes?: string[],
	excludedOriginCountryCodes?: string[],
	missingOriginCountry?: boolean,
	artistType?: string,
	artistGender?: string,
	artistBornYearFrom?: number | null,
	artistBornYearTo?: number | null,
	artistDied?: boolean,
	artistDiedYearFrom?: number | null,
	artistDiedYearTo?: number | null,
	artistFoundedYearFrom?: number | null,
	artistFoundedYearTo?: number | null,
	artistDissolved?: boolean,
	artistDissolvedYearFrom?: number | null,
	artistDissolvedYearTo?: number | null,
};

export type BrowseRequest = {
	view?: string,
	searchText?: string,
	filters?: BrowseFilters,
	sort?: BrowseSort,
	limit?: number,
	offset?: number,
};

export type BrowseSort = {
	field?: string,
	direction?: string,
};

export type ChartConfig = ChartConfig_Serialize | ChartConfig_Deserialize;

export type ChartConfig_Deserialize = {
	request: BrowseRequest,
	rankingMetric: string,
	sortField?: string | null,
	ratingCompletenessMin?: number | null,
	ratingCompletenessMax?: number | null,
	ratingCompletenessThreshold?: number | null,
	sortDirection: string,
	resultLimit: number,
	visibleColumns: string[],
	exportColumns: string[],
	viewMode: string,
	gridCoverSize?: number,
};

export type ChartConfig_Serialize = {
	request: BrowseRequest,
	rankingMetric: string,
	sortField: string | null,
	ratingCompletenessMin: number | null,
	ratingCompletenessMax: number | null,
	ratingCompletenessThreshold?: number | null,
	sortDirection: string,
	resultLimit: number,
	visibleColumns: string[],
	exportColumns: string[],
	viewMode: string,
	gridCoverSize: number,
};

export type ExportPlaylistRequest = ExportPlaylistRequest_Serialize | ExportPlaylistRequest_Deserialize;

export type ExportPlaylistRequest_Deserialize = {
	name: string,
	playlist: AiPlaylist_Deserialize,
};

export type ExportPlaylistRequest_Serialize = {
	name: string,
	playlist: AiPlaylist_Serialize,
};

export type ExportResult = {
	path: string,
	format: string,
	rowCount: number,
};

export type ExternalDiscoveryItem = {
	id: string,
	entity: string,
	title: string,
	artist: string,
	anchor: string | null,
	year: number | null,
	country: string | null,
	itemType: string | null,
	tags: string[],
	score: number,
	evidence: string,
	url: string,
};

export type ExternalDiscoveryResponse = {
	prompt: string,
	title: string,
	summary: string,
	plan: AiExternalDiscoveryPlan,
	items: ExternalDiscoveryItem[],
	source: string,
	fetchedAt: string,
	catalogCandidateCount: number,
	excludedOwnedCount: number,
	limitations: string[],
};

export type MixtapeConfig = {
	briefs: [string, string],
	minutes: [number, number],
	maxArtist: number,
	maxAlbum: number,
	weights: Weights,
};

export type MixtapeDraft = {
	version: number,
	config: MixtapeConfig,
	pool: AiPlaylistTrack[],
	notes: { [key in string]: string },
	assessments: Assessment[],
	scoredBriefs: [string, string] | null,
	sides: [Slot[], Slot[]],
};

export type PlaylistAutomationStatus = {
	smart: boolean,
	lastEvaluatedAt: string | null,
	lastError: string | null,
	desiredCount: number,
};

export type SaveAiSnapshotRequest = SaveAiSnapshotRequest_Serialize | SaveAiSnapshotRequest_Deserialize;

export type SaveAiSnapshotRequest_Deserialize = {
	title: string,
	content: AiSnapshotContent_Deserialize,
};

export type SaveAiSnapshotRequest_Serialize = {
	title: string,
	content: AiSnapshotContent_Serialize,
};

export type SavePlaylistRequest = SavePlaylistRequest_Serialize | SavePlaylistRequest_Deserialize;

export type SavePlaylistRequest_Deserialize = {
	id?: number | null,
	name: string,
	playlist: AiPlaylist_Deserialize,
};

export type SavePlaylistRequest_Serialize = {
	id: number | null,
	name: string,
	playlist: AiPlaylist_Serialize,
};

export type SavedPlaylist = SavedPlaylist_Serialize | SavedPlaylist_Deserialize;

export type SavedPlaylist_Deserialize = {
	id: number,
	name: string,
	playlist: AiPlaylist_Deserialize,
	libraryImportRunId: number | null,
	libraryImportedAt: string | null,
	libraryAlbumCount: number,
	libraryTrackCount: number,
	createdAt: string,
	updatedAt: string,
	automation: PlaylistAutomationStatus,
};

export type SavedPlaylist_Serialize = {
	id: number,
	name: string,
	playlist: AiPlaylist_Serialize,
	libraryImportRunId: number | null,
	libraryImportedAt: string | null,
	libraryAlbumCount: number,
	libraryTrackCount: number,
	createdAt: string,
	updatedAt: string,
	automation: PlaylistAutomationStatus,
};

export type Score = {
	score: number | null,
	confidence: number | null,
};

export type SetPlaylistAutomationRequest = {
	id: number,
	smart: boolean,
};

export type Slot = {
	trackId: number,
	role: string,
	locked: boolean,
	transitionToNext: boolean,
};

export type SmartPlaylistRefreshResult = SmartPlaylistRefreshResult_Serialize | SmartPlaylistRefreshResult_Deserialize;

export type SmartPlaylistRefreshResult_Deserialize = {
	playlist: SavedPlaylist_Deserialize,
	desiredCount: number,
	previewCount: number,
	refreshedAt: string,
};

export type SmartPlaylistRefreshResult_Serialize = {
	playlist: SavedPlaylist_Serialize,
	desiredCount: number,
	previewCount: number,
	refreshedAt: string,
};

export type TextFilter = {
	operator?: string,
	value?: string,
};

export type Weights = {
	atmosphere: number | null,
	role: number | null,
	rating: number | null,
};

