// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	usenetBootstrap: () => __TAURI_INVOKE<UsenetBootstrap>("usenet_bootstrap"),
	usenetSaveProfile: (request: SaveUsenetProfileRequest) => __TAURI_INVOKE<UsenetBootstrap>("usenet_save_profile", { request }),
	usenetReset: () => __TAURI_INVOKE<UsenetBootstrap>("usenet_reset"),
	usenetTestConnections: () => __TAURI_INVOKE<UsenetConnectionTest>("usenet_test_connections"),
	usenetSearch: (request: UsenetSearchRequest) => __TAURI_INVOKE<UsenetSearchResponse>("usenet_search", { request }),
	usenetTransfersSnapshot: () => __TAURI_INVOKE<UsenetTransferQueue>("usenet_transfers_snapshot"),
	usenetEnqueueDownload: (request: UsenetDownloadRequest) => __TAURI_INVOKE<UsenetTransferQueue>("usenet_enqueue_download", { request }),
	usenetClearCompleted: () => __TAURI_INVOKE<UsenetTransferQueue>("usenet_clear_completed"),
	localSharesSnapshot: () => __TAURI_INVOKE<LocalSharesSnapshot>("local_shares_snapshot"),
	localSharesAdd: (path: string) => __TAURI_INVOKE<LocalSharesSnapshot>("local_shares_add", { path }),
	localSharesRemove: (id: string) => __TAURI_INVOKE<LocalSharesSnapshot>("local_shares_remove", { id }),
	localSharesSetEnabled: (id: string, enabled: boolean) => __TAURI_INVOKE<LocalSharesSnapshot>("local_shares_set_enabled", { id, enabled }),
	localSharesRescan: () => __TAURI_INVOKE<LocalSharesSnapshot>("local_shares_rescan"),
	localSharesSetUploadSlots: (uploadSlots: number) => __TAURI_INVOKE<LocalSharesSnapshot>("local_shares_set_upload_slots", { uploadSlots }),
	uploadsSnapshot: () => __TAURI_INVOKE<UploadQueueSnapshot>("uploads_snapshot"),
	uploadCancel: (id: string) => __TAURI_INVOKE<UploadQueueSnapshot>("upload_cancel", { id }),
	uploadClearFinished: () => __TAURI_INVOKE<UploadQueueSnapshot>("upload_clear_finished"),
	transfersSnapshot: () => __TAURI_INVOKE<TransferQueueSnapshot>("transfers_snapshot"),
	transferSetMaxConcurrentDownloads: (maxConcurrentDownloads: number) => __TAURI_INVOKE<TransferQueueSnapshot>("transfer_set_max_concurrent_downloads", { maxConcurrentDownloads }),
	transferEnqueueRelease: (request: EnqueueReleaseRequest) => __TAURI_INVOKE<TransferQueueSnapshot>("transfer_enqueue_release", { request }),
	transferPauseRelease: (releaseId: string) => __TAURI_INVOKE<TransferQueueSnapshot>("transfer_pause_release", { releaseId }),
	transferResumeRelease: (releaseId: string) => __TAURI_INVOKE<TransferQueueSnapshot>("transfer_resume_release", { releaseId }),
	transferCancelRelease: (releaseId: string) => __TAURI_INVOKE<TransferQueueSnapshot>("transfer_cancel_release", { releaseId }),
	transferClearCompleted: () => __TAURI_INVOKE<TransferQueueSnapshot>("transfer_clear_completed"),
	transferRevealReleasePath: (releaseId: string) => __TAURI_INVOKE<string>("transfer_reveal_release_path", { releaseId }),
	connectionBootstrap: () => __TAURI_INVOKE<ConnectionBootstrap>("connection_bootstrap"),
	connectionSaveProfile: (request: SaveConnectionRequest) => __TAURI_INVOKE<ConnectionBootstrap>("connection_save_profile", { request }),
	connectionConnect: () => __TAURI_INVOKE<ConnectionSnapshot>("connection_connect"),
	connectionDisconnect: () => __TAURI_INVOKE<ConnectionSnapshot>("connection_disconnect"),
	connectionReset: () => __TAURI_INVOKE<ConnectionBootstrap>("connection_reset"),
	searchSnapshot: () => __TAURI_INVOKE<SearchSnapshot[]>("search_snapshot"),
	searchStart: (clientId: string, query: string) => __TAURI_INVOKE<SearchSnapshot>("search_start", { clientId, query }),
	searchStop: (clientId: string) => __TAURI_INVOKE<{
	state: SearchState,
	token: number | null,
	clientId: string,
	query: string,
	resultCount: number,
	peerCount: number,
	message: string,
	startedAtMs: number | null,
	finishedAtMs: number | null,
} | null>("search_stop", { clientId }),
	searchClose: (clientId: string) => __TAURI_INVOKE<boolean>("search_close", { clientId }),
	getArtistBiography: (artistId: string, forceRefresh: boolean | null) => __TAURI_INVOKE<ArtistBiography>("get_artist_biography", { artistId, forceRefresh }),
	getAlbumReview: (albumId: string, forceRefresh: boolean | null) => __TAURI_INVOKE<AlbumReview>("get_album_review", { albumId, forceRefresh }),
	scoreMixtapeCandidates: (input: ScoreRequest) => __TAURI_INVOKE<ScoreResult>("score_mixtape_candidates", { input }),
	listSavedExternalDiscoveries: () => __TAURI_INVOKE<SavedExternalDiscovery[]>("list_saved_external_discoveries"),
	saveExternalDiscovery: (input: SaveExternalDiscoveryRequest) => __TAURI_INVOKE<SavedExternalDiscovery>("save_external_discovery", { input }),
	getAppUpdateStatus: () => __TAURI_INVOKE<UpdateSnapshot>("get_app_update_status"),
	checkAppUpdate: () => __TAURI_INVOKE<UpdateSnapshot>("check_app_update"),
	getMusicDoctorStatus: () => __TAURI_INVOKE<MusicDoctorStatus>("get_music_doctor_status"),
	getDeemixCredentialStatus: () => __TAURI_INVOKE<DeemixCredentialStatus>("get_deemix_credential_status"),
	saveDeemixArl: (arl: string) => __TAURI_INVOKE<DeemixConnectionTest>("save_deemix_arl", { arl }),
	deleteDeemixArl: () => __TAURI_INVOKE<DeemixCredentialStatus>("delete_deemix_arl"),
	testDeemixConnection: () => __TAURI_INVOKE<DeemixConnectionTest>("test_deemix_connection"),
	searchDeemixAlbums: (input: DeemixAlbumSearchRequest) => __TAURI_INVOKE<DeemixAlbumSearchResponse>("search_deemix_albums", { input }),
	downloadDeemixAlbum: (input: DeemixAlbumDownloadRequest) => __TAURI_INVOKE<DeemixAlbumDownloadSummary>("download_deemix_album", { input }),
	preflightDeemixAlbumDownload: (input: DeemixAlbumDownloadPreflightRequest) => __TAURI_INVOKE<DeemixAlbumDownloadPreflight>("preflight_deemix_album_download", { input }),
	importPublishedCharts: () => __TAURI_INVOKE<PublishedChartsImportSummary>("import_published_charts"),
	getPublishedChartCatalog: () => __TAURI_INVOKE<PublishedChartCatalog>("get_published_chart_catalog"),
	getPublishedArtistRankings: (chart: string, fromYear: number, toYear: number, fromWeek: string | null, toWeek: string | null, offset: number) => __TAURI_INVOKE<PublishedArtistRanking>("get_published_artist_rankings", { chart, fromYear, toYear, fromWeek, toWeek, offset }),
	getPublishedSongRankings: (chart: string, fromYear: number, toYear: number, fromWeek: string | null, toWeek: string | null, offset: number) => __TAURI_INVOKE<PublishedSongRanking>("get_published_song_rankings", { chart, fromYear, toYear, fromWeek, toWeek, offset }),
	getPublishedSongHistory: (chart: string, artist: string, title: string) => __TAURI_INVOKE<PublishedSongWeek[]>("get_published_song_history", { chart, artist, title }),
	listPublishedChartWeeks: (chart: string, year: number) => __TAURI_INVOKE<PublishedChartWeek[]>("list_published_chart_weeks", { chart, year }),
	getPublishedChartEntries: (chart: string, week: string, offset: number) => __TAURI_INVOKE<PublishedChartEntries>("get_published_chart_entries", { chart, week, offset }),
	getDiscogsCredentialStatus: () => __TAURI_INVOKE<DiscogsCredentialStatus>("get_discogs_credential_status"),
	saveDiscogsCredentials: (input: SaveDiscogsCredentialsRequest) => __TAURI_INVOKE<DiscogsConnectionTest>("save_discogs_credentials", { input }),
	deleteDiscogsCredentials: () => __TAURI_INVOKE<DiscogsCredentialStatus>("delete_discogs_credentials"),
	testDiscogsConnection: () => __TAURI_INVOKE<DiscogsConnectionTest>("test_discogs_connection"),
	getLastfmCredentialStatus: () => __TAURI_INVOKE<LastFmCredentialStatus>("get_lastfm_credential_status"),
	saveLastfmApiKey: (input: SaveLastFmApiKeyRequest) => __TAURI_INVOKE<LastFmConnectionTest>("save_lastfm_api_key", { input }),
	deleteLastfmApiKey: () => __TAURI_INVOKE<LastFmCredentialStatus>("delete_lastfm_api_key"),
	testLastfmConnection: () => __TAURI_INVOKE<LastFmConnectionTest>("test_lastfm_connection"),
	getLastfmArtistPopularity: (artistId: string, forceRefresh: boolean | null) => __TAURI_INVOKE<LastFmArtistPopularity>("get_lastfm_artist_popularity", { artistId, forceRefresh }),
	getLastfmArtistSimilarity: (artistId: string, forceRefresh: boolean | null) => __TAURI_INVOKE<LastFmArtistSimilarity>("get_lastfm_artist_similarity", { artistId, forceRefresh }),
	getLastfmArtistConstellationBranch: (rootArtistId: string, branchName: string, branchMbid: string | null) => __TAURI_INVOKE<LastFmArtistSimilarity>("get_lastfm_artist_constellation_branch", { rootArtistId, branchName, branchMbid }),
	getLastfmAlbumPopularity: (artistId: string, albumId: string) => __TAURI_INVOKE<LastFmAlbumPopularity>("get_lastfm_album_popularity", { artistId, albumId }),
	getLastfmRelatedAlbums: (albumId: string, forceRefresh: boolean | null) => __TAURI_INVOKE<LastFmRelatedAlbums>("get_lastfm_related_albums", { albumId, forceRefresh }),
	listWishList: () => __TAURI_INVOKE<WishListResponse>("list_wish_list"),
	addWishListItem: (input: AddWishListItemRequest) => __TAURI_INVOKE<WishListItem>("add_wish_list_item", { input }),
	removeWishListItem: (id: number) => __TAURI_INVOKE<null>("remove_wish_list_item", { id }),
	discoverWishListArtistAlbums: (input: WishListArtistAlbumDiscoveryRequest) => __TAURI_INVOKE<WishListArtistAlbumDiscoveryResponse>("discover_wish_list_artist_albums", { input }),
	refreshWishListArtistAlbumSummary: (input: WishListArtistAlbumDiscoveryRequest) => __TAURI_INVOKE<WishListArtistAlbumSummary>("refresh_wish_list_artist_album_summary", { input }),
	getLibraryCompletion: (input: {
	source?: string | null,
	decade?: number | null,
	yearFrom?: number | null,
	yearTo?: number | null,
} | null) => __TAURI_INVOKE<LibraryCompletionResponse>("get_library_completion", { input }),
	getLibraryCompletionVerificationStatus: () => __TAURI_INVOKE<LibraryCompletionVerificationStatus>("get_library_completion_verification_status"),
	startLibraryCompletionVerification: (input: StartLibraryCompletionVerificationRequest) => __TAURI_INVOKE<LibraryCompletionVerificationStatus>("start_library_completion_verification", { input }),
	setLibraryCompletionVerificationState: (input: SetLibraryCompletionVerificationStateRequest) => __TAURI_INVOKE<LibraryCompletionVerificationStatus>("set_library_completion_verification_state", { input }),
	retryLibraryCompletionVerificationFailures: (batchId: number) => __TAURI_INVOKE<LibraryCompletionVerificationStatus>("retry_library_completion_verification_failures", { batchId }),
	setLibraryCompletionDecision: (input: SetLibraryCompletionDecisionRequest) => __TAURI_INVOKE<LibraryCompletionDecision>("set_library_completion_decision", { input }),
	getLibraryCompletionArtists: (input: {
	source?: string | null,
	chartKind?: string | null,
	yearFrom?: number | null,
	yearTo?: number | null,
} | null) => __TAURI_INVOKE<LibraryCompletionArtistResponse>("get_library_completion_artists", { input }),
	getLibraryCompletionArtistVerificationStatus: () => __TAURI_INVOKE<LibraryCompletionArtistVerificationStatus>("get_library_completion_artist_verification_status"),
	startLibraryCompletionArtistVerification: (input: StartLibraryCompletionArtistVerificationRequest) => __TAURI_INVOKE<LibraryCompletionArtistVerificationStatus>("start_library_completion_artist_verification", { input }),
	setLibraryCompletionArtistVerificationState: (input: SetLibraryCompletionArtistVerificationStateRequest) => __TAURI_INVOKE<LibraryCompletionArtistVerificationStatus>("set_library_completion_artist_verification_state", { input }),
	retryLibraryCompletionArtistVerificationFailures: (batchId: number) => __TAURI_INVOKE<LibraryCompletionArtistVerificationStatus>("retry_library_completion_artist_verification_failures", { batchId }),
	confirmLibraryCompletionArtistMatch: (input: ConfirmLibraryCompletionArtistMatchRequest) => __TAURI_INVOKE<LibraryCompletionArtistCandidate>("confirm_library_completion_artist_match", { input }),
	setLibraryCompletionArtistDecision: (input: SetLibraryCompletionArtistDecisionRequest) => __TAURI_INVOKE<LibraryCompletionArtistDecision>("set_library_completion_artist_decision", { input }),
	enrichLibraryCompletionCover: (candidateId: string) => __TAURI_INVOKE<LibraryCompletionCoverEnrichment>("enrich_library_completion_cover", { candidateId }),
	getAiKeyStatus: () => __TAURI_INVOKE<AiKeyStatus>("get_ai_key_status"),
	saveOpenaiApiKey: (apiKey: string) => __TAURI_INVOKE<AiKeyStatus>("save_openai_api_key", { apiKey }),
	deleteOpenaiApiKey: () => __TAURI_INVOKE<AiKeyStatus>("delete_openai_api_key"),
	testOpenaiConnection: () => __TAURI_INVOKE<AiConnectionTest>("test_openai_connection"),
	compileNaturalLanguageQuery: (input: AiCompileRequest) => __TAURI_INVOKE<AiCompiledQuery_Serialize>("compile_natural_language_query", { input }),
	askCurrentView: (input: AiCurrentViewQuestion) => __TAURI_INVOKE<AiCurrentViewAnswer>("ask_current_view", { input }),
	researchMusic: (input: AiMusicResearchRequest) => __TAURI_INVOKE<AiMusicResearchAnswer>("research_music", { input }),
	analyzeLibrary: (input: AiLibraryAnalysisRequest) => __TAURI_INVOKE<AiLibraryAnalysis>("analyze_library", { input }),
	listAiSnapshots: (kind: string | null) => __TAURI_INVOKE<AiSnapshot_Serialize[]>("list_ai_snapshots", { kind }),
	saveAiSnapshot: (input: SaveAiSnapshotRequest_Deserialize) => __TAURI_INVOKE<AiSnapshot_Serialize>("save_ai_snapshot", { input }),
	deleteAiSnapshot: (id: number) => __TAURI_INVOKE<null>("delete_ai_snapshot", { id }),
	buildPlaylist: (input: AiPlaylistBuildRequest) => __TAURI_INVOKE<AiPlaylist_Serialize>("build_playlist", { input }),
	getJevKeyStatus: () => __TAURI_INVOKE<AiKeyStatus>("get_jev_key_status"),
	saveOpenrouterApiKey: (apiKey: string) => __TAURI_INVOKE<AiKeyStatus>("save_openrouter_api_key", { apiKey }),
	deleteOpenrouterApiKey: () => __TAURI_INVOKE<AiKeyStatus>("delete_openrouter_api_key"),
	testJevConnection: () => __TAURI_INVOKE<AiConnectionTest>("test_jev_connection"),
	exportAiMarkdown: (input: AiMarkdownExportRequest) => __TAURI_INVOKE<ExportResult>("export_ai_markdown", { input }),
	listSavedPlaylists: () => __TAURI_INVOKE<SavedPlaylist_Serialize[]>("list_saved_playlists"),
	savePlaylist: (input: SavePlaylistRequest_Deserialize) => __TAURI_INVOKE<SavedPlaylist_Serialize>("save_playlist", { input }),
	deleteSavedPlaylist: (id: number) => __TAURI_INVOKE<null>("delete_saved_playlist", { id }),
	setPlaylistAutomation: (input: SetPlaylistAutomationRequest) => __TAURI_INVOKE<SavedPlaylist_Serialize>("set_playlist_automation", { input }),
	refreshSmartPlaylist: (id: number) => __TAURI_INVOKE<SmartPlaylistRefreshResult_Serialize>("refresh_smart_playlist", { id }),
	discoverOutsideLibrary: (input: AiExternalDiscoveryRequest) => __TAURI_INVOKE<ExternalDiscoveryResponse>("discover_outside_library", { input }),
	exportPlaylist: (input: ExportPlaylistRequest_Deserialize) => __TAURI_INVOKE<ExportResult>("export_playlist", { input }),
};

/* Types */
export type AddWishListItemRequest = {
	entity: string,
	title: string,
	artist?: string,
	year: number | null,
	musicbrainzId: string | null,
	musicbrainzUrl: string | null,
	source?: string,
};

export type AiCompileRequest = {
	prompt: string,
	target: string,
	currentView?: string | null,
	followUp?: AiQueryFollowUpContext | null,
};

export type AiCompiledQuery = AiCompiledQuery_Serialize | AiCompiledQuery_Deserialize;

export type AiCompiledQuery_Deserialize = {
	target: string,
	queryIntent?: string,
	summary: string,
	request: BrowseRequest,
	chartConfig: ChartConfig_Deserialize | null,
	model: string,
	usage: AiUsage,
};

export type AiCompiledQuery_Serialize = {
	target: string,
	queryIntent: string,
	summary: string,
	request: BrowseRequest,
	chartConfig: ChartConfig_Serialize | null,
	model: string,
	usage: AiUsage,
};

export type AiConnectionTest = {
	model: string,
	message: string,
	usage: AiUsage,
};

export type AiCurrentViewAnswer = {
	answer: string,
	view: string,
	matchingRows: number,
	analysisCount: number,
	namedRowsShared: number,
	model: string,
	usage: AiUsage,
};

export type AiCurrentViewQuestion = {
	question: string,
	request: BrowseRequest,
	scopeLabel?: string | null,
	scopeToResultLimit?: boolean,
};

export type AiExternalDiscoveryPlan = {
	prompt: string,
	entity: string,
	count: number,
	year: number,
	yearFrom?: number,
	yearTo?: number,
	yearMeaning: string,
	genres: string[],
	countries: string[],
	keywords: string,
	title: string,
	summary: string,
	model: string,
	usage: AiUsage,
};

export type AiExternalDiscoveryRequest = {
	prompt: string,
};

export type AiKeyStatus = {
	configured: boolean,
	source: string,
	model: string,
};

export type AiLibraryAnalysis = {
	lens: string,
	headline: string,
	summary: string,
	findings: AiLibraryFinding[],
	nextQuestions: string[],
	profileSections: string[],
	aggregatePointsShared: number,
	model: string,
	usage: AiUsage,
};

export type AiLibraryAnalysisRequest = {
	lens: string,
	focus?: string,
};

export type AiLibraryFinding = {
	title: string,
	evidence: string,
	interpretation: string,
};

export type AiMarkdownExportRequest = {
	title: string,
	markdown: string,
};

export type AiMusicResearchAnswer = {
	answer: string,
	sources: AiMusicResearchSource[],
	model: string,
	usage: AiUsage,
	usedWebSearch: boolean,
	localInspectionCount: number,
};

export type AiMusicResearchContext = {
	workspace: string,
	selectedEntityType?: string | null,
	selectedEntityId?: string | null,
	selectedLabel?: string | null,
	selectedSubtitle?: string | null,
};

export type AiMusicResearchExchange = {
	question: string,
	result: AiMusicResearchAnswer,
};

export type AiMusicResearchRequest = {
	question: string,
	context: AiMusicResearchContext,
	conversation?: AiMusicResearchTurn[],
};

export type AiMusicResearchSource = {
	title: string,
	url: string,
};

export type AiMusicResearchTurn = {
	role: string,
	content: string,
};

export type AiPlaylist = AiPlaylist_Serialize | AiPlaylist_Deserialize;

export type AiPlaylistBuildRequest = {
	prompt: string,
	sourceRequest?: BrowseRequest | null,
};

export type AiPlaylistTrack = {
	trackId: number,
	albumId: string,
	album: string | null,
	albumArtist: string | null,
	displayArtist: string | null,
	title: string | null,
	genre: string | null,
	year: number | null,
	seconds: number,
	rating: number | null,
	loved: boolean,
	filePath: string | null,
	filename: string | null,
};

export type AiPlaylist_Deserialize = {
	mixtape?: MixtapeDraft | null,
	prompt: string,
	name: string,
	description: string,
	request: BrowseRequest,
	strategy: string,
	targetTrackCount: number,
	targetMinutes: number,
	maxTracksPerArtist: number,
	maxTracksPerAlbum: number,
	matchingTrackCount: number,
	candidateCount: number,
	totalSeconds: number,
	tracks: AiPlaylistTrack[],
	model: string,
	usage: AiUsage,
};

export type AiPlaylist_Serialize = {
	mixtape?: MixtapeDraft | null,
	prompt: string,
	name: string,
	description: string,
	request: BrowseRequest,
	strategy: string,
	targetTrackCount: number,
	targetMinutes: number,
	maxTracksPerArtist: number,
	maxTracksPerAlbum: number,
	matchingTrackCount: number,
	candidateCount: number,
	totalSeconds: number,
	tracks: AiPlaylistTrack[],
	model: string,
	usage: AiUsage,
};

export type AiQueryExchange = AiQueryExchange_Serialize | AiQueryExchange_Deserialize;

export type AiQueryExchange_Deserialize = {
	prompt: string,
	result: AiCompiledQuery_Deserialize,
	answer?: AiCurrentViewAnswer | null,
};

export type AiQueryExchange_Serialize = {
	prompt: string,
	result: AiCompiledQuery_Serialize,
	answer: AiCurrentViewAnswer | null,
};

export type AiQueryFollowUpContext = {
	previousPrompt: string,
	previousSummary: string,
	previousAnswer: string,
};

export type AiSnapshot = AiSnapshot_Serialize | AiSnapshot_Deserialize;

export type AiSnapshotContent = AiSnapshotContent_Serialize | AiSnapshotContent_Deserialize;

export type AiSnapshotContent_Deserialize = ({ kind: "search"; prompt: string; result: AiCompiledQuery_Deserialize; answer?: AiCurrentViewAnswer | null; exchanges?: AiQueryExchange_Deserialize[] }) & { context?: never; request?: never } | ({ kind: "chart"; prompt: string; result: AiCompiledQuery_Deserialize; answer?: AiCurrentViewAnswer | null; exchanges?: AiQueryExchange_Deserialize[] }) & { context?: never; request?: never } | ({ kind: "searchAnswer"; prompt: string; request: BrowseRequest; result: AiCurrentViewAnswer }) & { answer?: never; context?: never; exchanges?: never } | ({ kind: "chartAnswer"; prompt: string; request: BrowseRequest; result: AiCurrentViewAnswer }) & { answer?: never; context?: never; exchanges?: never } | ({ kind: "libraryAnalysis"; prompt: string; result: AiLibraryAnalysis }) & { answer?: never; context?: never; exchanges?: never; request?: never } | ({ kind: "musicResearch"; prompt: string; context: AiMusicResearchContext; exchanges: AiMusicResearchExchange[] }) & { answer?: never; request?: never; result?: never };

export type AiSnapshotContent_Serialize = ({ kind: "search"; prompt: string; result: AiCompiledQuery_Serialize; answer: AiCurrentViewAnswer | null; exchanges: AiQueryExchange_Serialize[] }) & { context?: never; request?: never } | ({ kind: "chart"; prompt: string; result: AiCompiledQuery_Serialize; answer: AiCurrentViewAnswer | null; exchanges: AiQueryExchange_Serialize[] }) & { context?: never; request?: never } | ({ kind: "searchAnswer"; prompt: string; request: BrowseRequest; result: AiCurrentViewAnswer }) & { answer?: never; context?: never; exchanges?: never } | ({ kind: "chartAnswer"; prompt: string; request: BrowseRequest; result: AiCurrentViewAnswer }) & { answer?: never; context?: never; exchanges?: never } | ({ kind: "libraryAnalysis"; prompt: string; result: AiLibraryAnalysis }) & { answer?: never; context?: never; exchanges?: never; request?: never } | ({ kind: "musicResearch"; prompt: string; context: AiMusicResearchContext; exchanges: AiMusicResearchExchange[] }) & { answer?: never; request?: never; result?: never };

export type AiSnapshot_Deserialize = {
	id: number,
	title: string,
	content: AiSnapshotContent_Deserialize,
	libraryImportRunId: number | null,
	libraryImportedAt: string | null,
	libraryAlbumCount: number,
	libraryTrackCount: number,
	createdAt: string,
};

export type AiSnapshot_Serialize = {
	id: number,
	title: string,
	content: AiSnapshotContent_Serialize,
	libraryImportRunId: number | null,
	libraryImportedAt: string | null,
	libraryAlbumCount: number,
	libraryTrackCount: number,
	createdAt: string,
};

export type AiUsage = {
	inputTokens: number | null,
	cachedInputTokens: number | null,
	outputTokens: number | null,
};

export type AlbumReview = {
	albumId: string,
	albumArtist: string,
	albumTitle: string,
	releaseGroupMbid: string | null,
	reviewId: string | null,
	review: string | null,
	reviewerName: string | null,
	rating: number | null,
	language: string | null,
	reviewSource: string | null,
	sourceUrl: string | null,
	licenseId: string | null,
	licenseName: string | null,
	licenseUrl: string | null,
	fetchedAt: string | null,
	cached: boolean,
	stale: boolean,
	message: string,
};

export type ArtistBiography = {
	artistId: string,
	artistName: string,
	musicbrainzMbid: string | null,
	wikidataId: string | null,
	wikipediaLanguage: string | null,
	wikipediaTitle: string | null,
	biography: string | null,
	sourceUrl: string | null,
	fetchedAt: string | null,
	cached: boolean,
	stale: boolean,
	message: string,
};

export type Assessment = {
	trackId: number,
	sideA: Score,
	sideB: Score,
	opener: Score,
	builder: Score,
	breather: Score,
	closer: Score,
};

export type BrowseFilters = {
	albumIds?: string[],
	trackIds?: number[],
	artistKeys?: string[],
	albumTitle?: TextFilter,
	trackTitle?: TextFilter,
	albumArtist?: TextFilter,
	displayArtist?: TextFilter,
	publisher?: TextFilter,
	filePath?: TextFilter,
	filename?: TextFilter,
	hasTrackText?: string,
	genres?: string[],
	excludedGenres?: string[],
	missingFields?: string[],
	billboardRankMin?: number | null,
	billboardRankMax?: number | null,
	billboardSingleRankMin?: number | null,
	billboardSingleRankMax?: number | null,
	billboardSingleDebutDateFrom?: string | null,
	billboardSingleDebutDateTo?: string | null,
	billboardDebutWeekFrom?: string | null,
	billboardDebutWeekTo?: string | null,
	vgListaRankMin?: number | null,
	vgListaRankMax?: number | null,
	vgListaDebutWeekFrom?: string | null,
	vgListaDebutWeekTo?: string | null,
	officialUkRankMin?: number | null,
	officialUkRankMax?: number | null,
	officialUkDebutWeekFrom?: string | null,
	officialUkDebutWeekTo?: string | null,
	tiISkuddetRankMin?: number | null,
	tiISkuddetRankMax?: number | null,
	tiISkuddetDebutWeekFrom?: string | null,
	tiISkuddetDebutWeekTo?: string | null,
	norsktoppenRankMin?: number | null,
	norsktoppenRankMax?: number | null,
	norsktoppenDebutWeekFrom?: string | null,
	norsktoppenDebutWeekTo?: string | null,
	yearFrom?: number | null,
	yearTo?: number | null,
	releaseYearFrom?: number | null,
	releaseYearTo?: number | null,
	totalMinutesMin?: number | null,
	totalMinutesMax?: number | null,
	trackCountMin?: number | null,
	trackCountMax?: number | null,
	ratedTracksMin?: number | null,
	ratedTracksMax?: number | null,
	albumRatingMin?: number | null,
	albumRatingMax?: number | null,
	trackRatingMin?: number | null,
	trackRatingMax?: number | null,
	ratingCompletenessMin?: number | null,
	ratingCompletenessMax?: number | null,
	notFullyRated?: boolean,
	lovedTracksMin?: number | null,
	lovedTracksMax?: number | null,
	bitrateKbpsMin?: number | null,
	bitrateKbpsMax?: number | null,
	mixedAudioQuality?: boolean,
	originCountryCodes?: string[],
	excludedOriginCountryCodes?: string[],
	missingOriginCountry?: boolean,
	artistType?: string,
	artistGender?: string,
	artistBornYearFrom?: number | null,
	artistBornYearTo?: number | null,
	artistDied?: boolean,
	artistDiedYearFrom?: number | null,
	artistDiedYearTo?: number | null,
	artistFoundedYearFrom?: number | null,
	artistFoundedYearTo?: number | null,
	artistDissolved?: boolean,
	artistDissolvedYearFrom?: number | null,
	artistDissolvedYearTo?: number | null,
};

export type BrowseRequest = {
	view?: string,
	searchText?: string,
	filters?: BrowseFilters,
	sort?: BrowseSort,
	limit?: number,
	offset?: number,
};

export type BrowseSort = {
	field?: string,
	direction?: string,
};

export type ChartConfig = ChartConfig_Serialize | ChartConfig_Deserialize;

export type ChartConfig_Deserialize = {
	request: BrowseRequest,
	rankingMetric: string,
	sortField?: string | null,
	ratingCompletenessMin?: number | null,
	ratingCompletenessMax?: number | null,
	ratingCompletenessThreshold?: number | null,
	sortDirection: string,
	resultLimit: number,
	visibleColumns: string[],
	exportColumns: string[],
	viewMode: string,
	gridCoverSize?: number,
};

export type ChartConfig_Serialize = {
	request: BrowseRequest,
	rankingMetric: string,
	sortField: string | null,
	ratingCompletenessMin: number | null,
	ratingCompletenessMax: number | null,
	ratingCompletenessThreshold?: number | null,
	sortDirection: string,
	resultLimit: number,
	visibleColumns: string[],
	exportColumns: string[],
	viewMode: string,
	gridCoverSize: number,
};

export type ConfirmLibraryCompletionArtistMatchRequest = {
	artistId: string,
	candidate: WishListMusicBrainzCandidate,
};

export type ConnectionBootstrap = {
	profile: ConnectionProfile | null,
	suggestedProfile: ConnectionProfile,
	hasPassword: boolean,
	snapshot: ConnectionSnapshot,
	diagnosticsPath: string,
	diagnostics: DiagnosticEntry[],
	searchNetwork: DistributedSnapshot,
};

export type ConnectionProfile = {
	username: string,
	serverHost: string,
	serverPort: number,
	downloadDirectory: string,
	rememberPassword: boolean,
	autoConnect: boolean,
};

export type ConnectionSnapshot = {
	state: ConnectionState,
	username: string | null,
	server: string | null,
	message: string,
	attempt: number,
	connectedAtMs: number | null,
	retryInSeconds: number | null,
	updatedAtMs: number,
};

export type ConnectionState = "unconfigured" | "offline" | "connecting" | "authenticating" | "online" | "reconnecting" | "error";

export type DeemixAlbumDownloadPreflight = {
	alreadyDownloaded: boolean,
	destinationPath: string | null,
	downloadedAt: string | null,
	message: string,
};

export type DeemixAlbumDownloadPreflightRequest = {
	albumId: string,
	wishListItemId?: number | null,
	musicbrainzReleaseGroupId?: string | null,
	artist: string,
	album: string,
	year: number | null,
};

export type DeemixAlbumDownloadRequest = {
	albumId: string,
	requestId: string,
	wishListItemId?: number | null,
	musicbrainzReleaseGroupId?: string | null,
	expectedArtist?: string,
	expectedAlbum?: string,
	expectedYear: number | null,
	allowDuplicate?: boolean,
};

export type DeemixAlbumDownloadSummary = {
	requestId: string,
	albumId: string,
	artist: string,
	album: string,
	year: number | null,
	quality: string,
	destinationPath: string,
	coverPath: string | null,
	warning: string | null,
	trackCount: number,
	completedAt: string,
};

export type DeemixAlbumMatch = {
	id: string,
	title: string,
	artist: string,
	year: number | null,
	trackCount: number | null,
	recordType: string | null,
	explicit: boolean,
	deezerUrl: string,
	matchScore: number,
	matchLevel: string,
	downloadedAt: string | null,
	downloadedPath: string | null,
};

export type DeemixAlbumSearchRequest = {
	title: string,
	artist: string,
	year?: number | null,
	limit?: number | null,
};

export type DeemixAlbumSearchResponse = {
	query: string,
	total: number,
	matches: DeemixAlbumMatch[],
	searchedAt: string,
};

export type DeemixConnectionTest = {
	accountName: string,
	userId: string,
	country: string | null,
	canStreamHq: boolean,
	canStreamLossless: boolean,
	message: string,
};

export type DeemixCredentialStatus = {
	configured: boolean,
	source: string,
};

export type DiagnosticEntry = {
	timestampMs: number,
	level: string,
	event: string,
	message: string,
};

export type DiscogsConnectionTest = {
	authenticated: boolean,
	rateLimit: number | null,
	rateLimitRemaining: number | null,
	message: string,
};

export type DiscogsCredentialStatus = {
	configured: boolean,
	source: string,
};

export type DistributedSnapshot = {
	state: DistributedState,
	message: string,
	branchLevel: number | null,
	searchesReceived: number,
	searchesMatched: number,
	searchesAnswered: number,
	searchesIgnored: number,
	updatedAtMs: number,
};

export type DistributedState = "offline" | "discovering" | "connected" | "branchRoot";

export type EnqueueReleaseFileRequest = {
	title: string,
	remoteFilename: string,
	sizeBytes: number,
};

export type EnqueueReleaseRequest = {
	title: string,
	username: string,
	remoteFolder: string,
	files: EnqueueReleaseFileRequest[],
	expectedTrackCount?: number | null,
	releaseGroupId?: string | null,
	alternatives?: ReleaseAlternativeSource[],
};

export type ExportPlaylistRequest = ExportPlaylistRequest_Serialize | ExportPlaylistRequest_Deserialize;

export type ExportPlaylistRequest_Deserialize = {
	name: string,
	playlist: AiPlaylist_Deserialize,
};

export type ExportPlaylistRequest_Serialize = {
	name: string,
	playlist: AiPlaylist_Serialize,
};

export type ExportResult = {
	path: string,
	format: string,
	rowCount: number,
};

export type ExternalDiscoveryItem = {
	id: string,
	entity: string,
	title: string,
	artist: string,
	anchor: string | null,
	year: number | null,
	country: string | null,
	itemType: string | null,
	tags: string[],
	score: number,
	evidence: string,
	url: string,
};

export type ExternalDiscoveryResponse = {
	prompt: string,
	title: string,
	summary: string,
	plan: AiExternalDiscoveryPlan,
	items: ExternalDiscoveryItem[],
	source: string,
	fetchedAt: string,
	catalogCandidateCount: number,
	excludedOwnedCount: number,
	limitations: string[],
};

export type LastFmAlbumPopularity = {
	artistId: string,
	albumId: string,
	sourceUrl: string | null,
	fetchedAt: string | null,
	totalTracks: number,
	resolvedTracks: number,
	availableTracks: number,
	stale: boolean,
	tracks: LastFmAlbumTrackPopularity[],
	message: string,
};

export type LastFmAlbumTrackPopularity = {
	trackId: number,
	title: string,
	listeners: number,
	playCount: number,
	albumRank: number | null,
	sourceUrl: string | null,
};

export type LastFmArtistPopularity = {
	artistId: string,
	artistName: string,
	sourceUrl: string | null,
	fetchedAt: string | null,
	cached: boolean,
	stale: boolean,
	tracks: LastFmPopularTrack[],
	message: string,
};

export type LastFmArtistSimilarity = {
	artistId: string,
	artistName: string,
	sourceUrl: string | null,
	fetchedAt: string | null,
	cached: boolean,
	stale: boolean,
	artists: LastFmSimilarArtist[],
	message: string,
};

export type LastFmConnectionTest = {
	authenticated: boolean,
	message: string,
};

export type LastFmCredentialStatus = {
	configured: boolean,
	source: string,
};

export type LastFmPopularTrack = {
	rank: number,
	trackId: number,
	albumId: string,
	album: string | null,
	year: number | null,
	title: string,
	artist: string,
	listeners: number,
	playCount: number,
	seconds: number | null,
	sourceUrl: string | null,
};

export type LastFmRelatedAlbum = {
	rank: number,
	artistName: string,
	artistMbid: string | null,
	albumTitle: string,
	albumMbid: string | null,
	sourceUrl: string | null,
	sharedTags: string[],
	artistSimilarity: number | null,
	localAlbumId: string | null,
	localAlbumArtist: string | null,
	localAlbumTitle: string | null,
	localYear: number | null,
	localCoverPath: string | null,
	localCoverMimeType: string | null,
};

export type LastFmRelatedAlbums = {
	albumId: string,
	albumArtist: string,
	albumTitle: string,
	sourceUrl: string | null,
	sourceTags: string[],
	fetchedAt: string | null,
	cached: boolean,
	stale: boolean,
	albums: LastFmRelatedAlbum[],
	message: string,
};

export type LastFmSimilarArtist = {
	rank: number,
	name: string,
	musicbrainzMbid: string | null,
	matchScore: number | null,
	sourceUrl: string | null,
	localArtistId: string | null,
	localArtistName: string | null,
	localAlbumCount: number,
	portraitAvailable: boolean,
	representativeAlbumId: string | null,
	representativeAlbum: string | null,
	representativeCoverPath: string | null,
};

export type LibraryCompletionArtistCandidate = {
	id: string,
	artist: string,
	firstChartYear: number,
	confidence: string,
	status: string,
	wishListItemId: number | null,
	verificationStatus: string,
	verificationMessage: string | null,
	verificationCheckedAt: string | null,
	musicbrainzVerificationStatus: string | null,
	musicbrainzVerificationMessage: string | null,
	musicbrainzId: string | null,
	musicbrainzUrl: string | null,
	officialAlbumCount: number,
	discogsVerificationStatus: string | null,
	discogsVerificationMessage: string | null,
	discogsMasterId: string | null,
	discogsUrl: string | null,
	discogsStudioAlbumTitle: string | null,
	evidence: LibraryCompletionArtistEvidence[],
};

export type LibraryCompletionArtistDecision = {
	artistId: string,
	status: string,
	wishListItemId: number | null,
	missingAlbumCount: number | null,
	message: string,
	updatedAt: string,
};

export type LibraryCompletionArtistEvidence = {
	source: string,
	chartKind: string,
	label: string,
	bestRank: number,
	firstYear: number,
	lastYear: number,
	appearances: number,
};

export type LibraryCompletionArtistRequest = {
	source?: string | null,
	chartKind?: string | null,
	yearFrom?: number | null,
	yearTo?: number | null,
};

export type LibraryCompletionArtistResponse = {
	generatedAt: string,
	totalChartArtists: number,
	ownedArtistCount: number,
	totalCandidates: number,
	returnedCandidates: number,
	truncated: boolean,
	candidates: LibraryCompletionArtistCandidate[],
};

export type LibraryCompletionArtistVerificationBatch = {
	id: number,
	label: string,
	state: string,
	totalCount: number,
	queuedCount: number,
	checkingCount: number,
	verifiedCount: number,
	noMatchCount: number,
	ambiguousCount: number,
	failedCount: number,
	completedCount: number,
	estimatedSecondsRemaining: number,
	createdAt: string,
	updatedAt: string,
	completedAt: string | null,
};

export type LibraryCompletionArtistVerificationItemSummary = {
	artistId: string,
	artist: string,
	state: string,
	provider: string,
	message: string | null,
	officialAlbumCount: number,
	updatedAt: string,
};

export type LibraryCompletionArtistVerificationStatus = {
	batch: LibraryCompletionArtistVerificationBatch | null,
	recentItems: LibraryCompletionArtistVerificationItemSummary[],
};

export type LibraryCompletionAtlasCell = {
	source: string,
	label: string,
	decade: number,
	owned: number,
	candidates: number,
	verified: number,
	wanted: number,
	needsReview: number,
	excluded: number,
	total: number,
};

export type LibraryCompletionCandidate = {
	id: string,
	artist: string,
	title: string,
	chartYear: number,
	confidence: string,
	status: string,
	wishListItemId: number | null,
	musicbrainzId: string | null,
	musicbrainzUrl: string | null,
	coverUrl: string | null,
	coverStatus: string | null,
	coverProvider: string | null,
	coverMessage: string | null,
	coverCheckedAt: string | null,
	verificationStatus: string,
	verificationProvider: string | null,
	verificationMessage: string | null,
	verificationCheckedAt: string | null,
	musicbrainzVerificationStatus: string | null,
	musicbrainzVerificationMessage: string | null,
	discogsVerificationStatus: string | null,
	discogsVerificationMessage: string | null,
	discogsMasterId: string | null,
	discogsUrl: string | null,
	evidence: LibraryCompletionEvidence[],
};

export type LibraryCompletionCoverEnrichment = {
	candidateId: string,
	state: string,
	provider: string | null,
	message: string,
	hasCover: boolean,
	checkedAt: string,
};

export type LibraryCompletionDecision = {
	candidateId: string,
	status: string,
	wishListItemId: number | null,
	musicbrainzId: string | null,
	musicbrainzUrl: string | null,
	updatedAt: string,
};

export type LibraryCompletionEvidence = {
	source: string,
	label: string,
	bestRank: number,
	firstYear: number,
	lastYear: number,
	appearances: number,
};

export type LibraryCompletionRequest = {
	source?: string | null,
	decade?: number | null,
	yearFrom?: number | null,
	yearTo?: number | null,
};

export type LibraryCompletionResponse = {
	generatedAt: string,
	totalChartAlbums: number,
	totalCandidates: number,
	returnedCandidates: number,
	truncated: boolean,
	candidates: LibraryCompletionCandidate[],
	atlas: LibraryCompletionAtlasCell[],
};

export type LibraryCompletionVerificationBatch = {
	id: number,
	label: string,
	source: string | null,
	decade: number | null,
	state: string,
	totalCount: number,
	queuedCount: number,
	checkingCount: number,
	verifiedCount: number,
	discogsVerifiedCount: number,
	noMatchCount: number,
	ambiguousCount: number,
	failedCount: number,
	cachedCount: number,
	completedCount: number,
	estimatedSecondsRemaining: number,
	createdAt: string,
	updatedAt: string,
	completedAt: string | null,
};

export type LibraryCompletionVerificationItemSummary = {
	candidateId: string,
	artist: string,
	title: string,
	state: string,
	provider: string,
	message: string | null,
	musicbrainzId: string | null,
	musicbrainzUrl: string | null,
	musicbrainzVerificationStatus: string | null,
	musicbrainzVerificationMessage: string | null,
	discogsVerificationStatus: string | null,
	discogsVerificationMessage: string | null,
	discogsMasterId: string | null,
	discogsUrl: string | null,
	updatedAt: string,
};

export type LibraryCompletionVerificationStatus = {
	batch: LibraryCompletionVerificationBatch | null,
	recentItems: LibraryCompletionVerificationItemSummary[],
};

export type LocalSharesSnapshot = {
	roots: SharedRootSnapshot[],
	uploadSlots: number,
	scanning: boolean,
	totalFileCount: number,
	totalDirectoryCount: number,
	totalSizeBytes: number,
	lastScanAtMs: number | null,
};

export type MixtapeConfig = {
	briefs: [string, string],
	minutes: [number, number],
	maxArtist: number,
	maxAlbum: number,
	weights: Weights,
};

export type MixtapeDraft = {
	version: number,
	config: MixtapeConfig,
	pool: AiPlaylistTrack[],
	notes: { [key in string]: string },
	assessments: Assessment[],
	scoredBriefs: [string, string] | null,
	sides: [Slot[], Slot[]],
};

export type MusicDoctorBitrateStat = {
	band: string,
	sortOrder: number,
	fileCount: number,
	totalBytes: number,
};

export type MusicDoctorFormatStat = {
	format: string,
	fileCount: number,
	totalBytes: number,
};

export type MusicDoctorSource = {
	path: string,
	enabled: boolean,
	lastScanAt: string | null,
	fileCount: number,
	totalBytes: number,
};

export type MusicDoctorStatus = {
	databasePath: string,
	resolvedPath: string,
	exists: boolean,
	valid: boolean,
	state: string,
	message: string,
	schemaVersion: number | null,
	fileSizeBytes: number,
	latestScanId: number | null,
	latestScanStatus: string | null,
	latestScanCompletedAt: string | null,
	sourceCount: number,
	totalFiles: number,
	audioFiles: number,
	audioAlbums: number,
	matchedTracks: number,
	unmatchedLibraryTracks: number,
	unmatchedDoctorAudio: number,
	fileIssueCount: number,
	lastSyncedAt: string | null,
	needsSync: boolean,
	syncInProgress: boolean,
	sources: MusicDoctorSource[],
	formatStats: MusicDoctorFormatStat[],
	bitrateStats: MusicDoctorBitrateStat[],
};

export type PatchRepairSnapshot = {
	reason: string,
	originalUsername: string | null,
	originalRemoteFilename: string | null,
	requestedAtMs: number,
	repairedAtMs?: number | null,
	warnings?: string[],
};

export type PlaylistAutomationStatus = {
	smart: boolean,
	lastEvaluatedAt: string | null,
	lastError: string | null,
	desiredCount: number,
};

export type PublishedArtistRanking = {
	totalArtists: number,
	chartWeeks: number,
	totalEntries: number,
	artists: PublishedArtistRow[],
};

export type PublishedArtistRow = {
	rank: number,
	artist: string,
	numberOneWeeks: number,
	chartWeeks: number,
	appearances: number,
	bestPosition: number,
	/**  Other printed spellings merged into this row, most printed first. */
	printedVariants: string[],
};

export type PublishedChartCatalog = {
	importedYears: number,
	inventoryYears: number,
	needsImport: boolean,
	totalRows: number,
	series: PublishedChartSeries[],
};

export type PublishedChartEntries = {
	totalRows: number,
	entries: PublishedChartEntry[],
};

export type PublishedChartEntry = {
	id: number,
	position: number,
	lastWeek: string,
	weeksOnChart: string,
	entryStatus: string,
	movement: string,
	title: string,
	artist: string,
	numberOneMarker: string,
	label: string,
	format: string,
	catalogueNumber: string,
	releaseType: string,
	duration: string,
	peakPosition: string,
	entryDate: string,
	peakDate: string,
	bpiAward: string,
	sourcePage: string,
	book: string,
};

export type PublishedChartSeries = {
	chart: string,
	years: number[],
	firstWeek: string,
	lastWeek: string,
	rows: number,
};

export type PublishedChartWeek = {
	weekEnding: string,
	rows: number,
};

export type PublishedChartsImportSummary = {
	sourcePath: string,
	yearsImported: number,
	chartSeries: number,
	rowsImported: number,
	durationMs: number,
};

export type PublishedSongRanking = {
	totalSongs: number,
	chartWeeks: number,
	totalEntries: number,
	songs: PublishedSongRow[],
};

export type PublishedSongRow = {
	rank: number,
	artist: string,
	title: string,
	numberOneWeeks: number,
	chartWeeks: number,
	appearances: number,
	bestPosition: number,
	firstWeek: string,
	lastWeek: string,
	/**  Other printed artist – title spellings merged into this row. */
	printedVariants: string[],
};

export type PublishedSongWeek = {
	weekEnding: string,
	position: number,
	entryStatus: string,
	entryDate: string,
};

export type ReleaseAlternativeFile = {
	title: string,
	remoteFilename: string,
	sizeBytes: number,
};

export type ReleaseAlternativeSource = {
	username: string,
	remoteFolder: string,
	files: ReleaseAlternativeFile[],
};

export type SaveAiSnapshotRequest = SaveAiSnapshotRequest_Serialize | SaveAiSnapshotRequest_Deserialize;

export type SaveAiSnapshotRequest_Deserialize = {
	title: string,
	content: AiSnapshotContent_Deserialize,
};

export type SaveAiSnapshotRequest_Serialize = {
	title: string,
	content: AiSnapshotContent_Serialize,
};

export type SaveConnectionRequest = {
	profile: ConnectionProfile,
	password: string | null,
};

export type SaveDiscogsCredentialsRequest = {
	consumerKey: string,
	consumerSecret: string,
};

export type SaveExternalDiscoveryRequest = {
	id: number | null,
	name: string,
	response: ExternalDiscoveryResponse,
};

export type SaveLastFmApiKeyRequest = {
	apiKey: string,
};

export type SavePlaylistRequest = SavePlaylistRequest_Serialize | SavePlaylistRequest_Deserialize;

export type SavePlaylistRequest_Deserialize = {
	id?: number | null,
	name: string,
	playlist: AiPlaylist_Deserialize,
};

export type SavePlaylistRequest_Serialize = {
	id: number | null,
	name: string,
	playlist: AiPlaylist_Serialize,
};

export type SaveUsenetProfileRequest = {
	profile: UsenetProfile,
	prowlarrApiKey: string | null,
	newsPassword: string | null,
};

export type SavedExternalDiscovery = {
	id: number,
	name: string,
	response: ExternalDiscoveryResponse,
	libraryImportRunId: number | null,
	libraryImportedAt: string | null,
	libraryAlbumCount: number,
	libraryTrackCount: number,
	createdAt: string,
	updatedAt: string,
};

export type SavedPlaylist = SavedPlaylist_Serialize | SavedPlaylist_Deserialize;

export type SavedPlaylist_Deserialize = {
	id: number,
	name: string,
	playlist: AiPlaylist_Deserialize,
	libraryImportRunId: number | null,
	libraryImportedAt: string | null,
	libraryAlbumCount: number,
	libraryTrackCount: number,
	createdAt: string,
	updatedAt: string,
	automation: PlaylistAutomationStatus,
};

export type SavedPlaylist_Serialize = {
	id: number,
	name: string,
	playlist: AiPlaylist_Serialize,
	libraryImportRunId: number | null,
	libraryImportedAt: string | null,
	libraryAlbumCount: number,
	libraryTrackCount: number,
	createdAt: string,
	updatedAt: string,
	automation: PlaylistAutomationStatus,
};

export type Score = {
	score: number | null,
	confidence: number | null,
};

export type ScoreRequest = {
	tracks: AiPlaylistTrack[],
	briefs: [string, string],
	notes: { [key in string]: string },
};

export type ScoreResult = {
	assessments: Assessment[],
	model: string,
	usage: AiUsage,
};

export type SearchSnapshot = {
	state: SearchState,
	token: number | null,
	clientId: string,
	query: string,
	resultCount: number,
	peerCount: number,
	message: string,
	startedAtMs: number | null,
	finishedAtMs: number | null,
};

export type SearchState = "idle" | "searching" | "completed" | "stopped" | "error";

export type SetLibraryCompletionArtistDecisionRequest = {
	artistId: string,
	artist: string,
	status: string,
};

export type SetLibraryCompletionArtistVerificationStateRequest = {
	batchId: number,
	state: string,
};

export type SetLibraryCompletionDecisionRequest = {
	candidateId: string,
	artist: string,
	title: string,
	chartYear: number,
	source: string,
	status: string,
	wishListItemId: number | null,
	musicbrainzId: string | null,
	musicbrainzUrl: string | null,
};

export type SetLibraryCompletionVerificationStateRequest = {
	batchId: number,
	state: string,
};

export type SetPlaylistAutomationRequest = {
	id: number,
	smart: boolean,
};

export type SharedRootSnapshot = {
	id: string,
	path: string,
	alias: string,
	enabled: boolean,
	fileCount: number,
	directoryCount: number,
	totalSizeBytes: number,
	error: string | null,
};

export type Slot = {
	trackId: number,
	role: string,
	locked: boolean,
	transitionToNext: boolean,
};

export type SmartPlaylistRefreshResult = SmartPlaylistRefreshResult_Serialize | SmartPlaylistRefreshResult_Deserialize;

export type SmartPlaylistRefreshResult_Deserialize = {
	playlist: SavedPlaylist_Deserialize,
	desiredCount: number,
	previewCount: number,
	refreshedAt: string,
};

export type SmartPlaylistRefreshResult_Serialize = {
	playlist: SavedPlaylist_Serialize,
	desiredCount: number,
	previewCount: number,
	refreshedAt: string,
};

export type SoundcheckResult = {
	status: SoundcheckStatus,
	checkedAtMs: number,
	deep: boolean,
	codec: string | null,
	container: string | null,
	durationSeconds: number | null,
	bitrateKbps: number | null,
	sampleRate: number | null,
	bitsPerSample: number | null,
	channels: number | null,
	trackNumber: number | null,
	trackTotal: number | null,
	issues: string[],
};

export type SoundcheckStatus = "pending" | "passed" | "review" | "failed" | "unsupported";

export type StartLibraryCompletionArtistVerificationRequest = {
	artistIds?: string[],
	label: string | null,
};

export type StartLibraryCompletionVerificationRequest = {
	scope: string,
	candidateIds?: string[],
	source: string | null,
	decade: number | null,
	label: string | null,
};

export type TextFilter = {
	operator?: string,
	value?: string,
};

export type TransferQueueSnapshot = {
	transfers: TransferSnapshot[],
	activeCount: number,
	maxConcurrentDownloads: number,
	relaySuggestionMinutes: number,
	soundcheckEnabled: boolean,
	safetyState: TransferSafetyState,
};

export type TransferSafetyState = "running" | "draining" | "pausedForRestart";

export type TransferSnapshot = {
	id: string,
	releaseId?: string | null,
	releaseTitle?: string | null,
	releaseFolder?: string | null,
	fileIndex?: number | null,
	fileCount?: number | null,
	expectedTrackCount?: number | null,
	releaseGroupId?: string | null,
	title: string,
	username: string,
	remoteFilename: string,
	sizeBytes: number,
	transferredBytes: number,
	speedBytesPerSecond: number,
	etaSeconds: number | null,
	status: TransferStatus,
	queuePosition: number | null,
	localPath: string,
	error: string | null,
	retryCount?: number,
	retryAtMs?: number | null,
	waitingSinceMs?: number | null,
	verificationStatus?: VerificationStatus,
	verificationMessage?: string | null,
	verifiedAtMs?: number | null,
	filedAtMs?: number | null,
	soundcheck?: SoundcheckResult | null,
	patchRepair?: PatchRepairSnapshot | null,
	alternativeSources?: ReleaseAlternativeSource[],
	createdAtMs: number,
	updatedAtMs: number,
};

export type TransferStatus = "queued" | "retrying" | "requesting" | "remotelyQueued" | "connecting" | "downloading" | "paused" | "completed" | "failed";

export type UpdateInfo = {
	currentVersion: string,
	version: string,
	date: string | null,
	notes: string | null,
};

export type UpdateSnapshot = {
	checkedAt: string | null,
	info: UpdateInfo | null,
	error: string | null,
};

export type UploadQueueSnapshot = {
	uploads: UploadSnapshot[],
	activeCount: number,
	queuedCount: number,
	sessionUploadedBytes: number,
};

export type UploadSnapshot = {
	id: string,
	username: string,
	remoteFilename: string,
	filename: string,
	sizeBytes: number,
	transferredBytes: number,
	speedBytesPerSecond: number,
	etaSeconds: number | null,
	status: UploadStatus,
	queuePosition: number | null,
	error: string | null,
	createdAtMs: number,
	updatedAtMs: number,
};

export type UploadStatus = "queued" | "connecting" | "uploading" | "completed" | "failed" | "cancelled";

export type UsenetBootstrap = {
	profile: UsenetProfile,
	hasProwlarrApiKey: boolean,
	hasNewsPassword: boolean,
	extractorPath: string | null,
	par2Path: string | null,
};

export type UsenetConnectionTest = {
	prowlarrVersion: string,
	newsServer: string,
	extractorPath: string | null,
	par2Path: string | null,
	message: string,
};

export type UsenetDownloadRequest = {
	guid: string,
	title: string,
	indexer: string,
	downloadUrl: string,
	sizeBytes: number,
	expectedArtist: string,
	expectedAlbum: string,
	expectedYear: number | null,
	releaseGroupId: string | null,
};

export type UsenetProfile = {
	prowlarrUrl: string,
	newsHost: string,
	newsPort: number,
	useTls: boolean,
	username: string,
	downloadDirectory: string,
	connections: number,
};

export type UsenetSearchRequest = {
	title: string,
	artist: string,
	year?: number | null,
	limit?: number | null,
};

export type UsenetSearchResponse = {
	query: string,
	results: UsenetSearchResult[],
	searchedAt: string,
};

export type UsenetSearchResult = {
	guid: string,
	title: string,
	indexer: string,
	sizeBytes: number,
	ageDays: number,
	grabs: number | null,
	publishDate: string | null,
	downloadUrl: string,
	infoUrl: string | null,
	categories: string[],
	matchScore: number,
};

export type UsenetTransfer = {
	id: string,
	guid: string,
	title: string,
	indexer: string,
	status: UsenetTransferStatus,
	progressPercent: number,
	downloadedBytes: number,
	totalBytes: number,
	message: string,
	destinationPath: string | null,
	error: string | null,
	releaseGroupId: string | null,
	createdAt: string,
	updatedAt: string,
};

export type UsenetTransferQueue = {
	transfers: UsenetTransfer[],
	activeCount: number,
};

export type UsenetTransferStatus = "queued" | "fetchingNzb" | "downloading" | "verifying" | "repairing" | "extracting" | "completed" | "failed";

export type VerificationStatus = "pending" | "verified" | "missing" | "sizeMismatch";

export type Weights = {
	atmosphere: number | null,
	role: number | null,
	rating: number | null,
};

export type WishListArtistAlbumDiscoveryRequest = {
	wishListItemId: number,
};

export type WishListArtistAlbumDiscoveryResponse = {
	wishListItemId: number,
	artist: string,
	musicbrainzId: string,
	officialAlbumCount: number,
	searchedAlbumCount: number,
	matchedAlbumCount: number,
	truncated: boolean,
	albums: WishListArtistAlbumDiscoveryRow[],
	albumSummary: WishListArtistAlbumSummary,
	searchedAt: string,
};

export type WishListArtistAlbumDiscoveryRow = {
	releaseGroupId: string,
	title: string,
	year: number | null,
	secondaryTypes: string[],
	musicbrainzUrl: string,
	deemixMatches: DeemixAlbumMatch[],
	deemixError: string | null,
	downloadedDeezerAlbumId: string | null,
	downloadedPath: string | null,
	downloadedAt: string | null,
	inLibrary: boolean,
};

export type WishListArtistAlbumSummary = {
	officialAlbumCount: number,
	ownedAlbumCount: number,
	missingAlbumCount: number,
	missingAlbums: WishListMissingAlbum[],
	updatedAt: string,
};

export type WishListItem = {
	id: number,
	entity: string,
	title: string,
	artist: string,
	year: number | null,
	musicbrainzId: string | null,
	musicbrainzUrl: string | null,
	source: string,
	createdAt: string,
	downloadedDeezerAlbumId: string | null,
	downloadedPath: string | null,
	downloadedAt: string | null,
	artistAlbumSummary: WishListArtistAlbumSummary | null,
};

export type WishListMissingAlbum = {
	releaseGroupId: string,
	title: string,
	year: number | null,
	musicbrainzUrl: string,
};

export type WishListMusicBrainzCandidate = {
	entity: string,
	title: string,
	artist: string,
	year: number | null,
	musicbrainzId: string,
	musicbrainzUrl: string,
	disambiguation: string | null,
	country: string | null,
	score: number,
};

export type WishListResponse = {
	items: WishListItem[],
	autoRemovedCount: number,
};

