import type { DiscoveryResponse } from "../../types";
import timelineCover1 from "../../assets/album-timeline/timeline-cover-1.webp";
import timelineCover2 from "../../assets/album-timeline/timeline-cover-2.webp";
import timelineCover3 from "../../assets/album-timeline/timeline-cover-3.webp";
import timelineCover4 from "../../assets/album-timeline/timeline-cover-4.webp";
import timelineCover5 from "../../assets/album-timeline/timeline-cover-5.webp";
import timelineCover6 from "../../assets/album-timeline/timeline-cover-6.webp";

export const mockTimelineCoverUrls = [
  timelineCover1,
  timelineCover2,
  timelineCover3,
  timelineCover4,
  timelineCover5,
  timelineCover6,
];

export const mockDiscovery: DiscoveryResponse = {
  dailyEditionArchive: {
    availableDates: ["2026-08-11", "2026-08-10", "2026-08-09"],
    snapshotCreatedAt: "2026-08-11T08:00:00Z",
    retentionDays: 90,
    isArchived: false,
    today: "2026-08-11",
  },
  dailyEdition: {
    date: "2026-08-11",
    anniversaryYears: 50,
    anniversaries: [
      {
        albumId: "mb:mock-anniversary-1",
        album: "Station to Station",
        artist: "David Bowie",
        releaseYear: 1976,
        yearsAgo: 50,
        coverPath: mockTimelineCoverUrls[0],
        evidence: "Billboard #3 · Official UK #5 · VG-lista #6 · owned album",
        chartEvidence: ["Billboard #3", "Official UK #5", "VG-lista #6"],
        selectionReason:
          "Selected from your owned 1976 releases because its best imported album-chart position is #3. Matches: Billboard #3, Official UK #5, VG-lista #6. Local Album Score and loved tracks only break chart ties.",
      },
      {
        albumId: "mb:mock-anniversary-2",
        album: "Hejira",
        artist: "Joni Mitchell",
        releaseYear: 1976,
        yearsAgo: 50,
        coverPath: mockTimelineCoverUrls[1],
        evidence: "Billboard #13 · Official UK #11 · owned album",
        chartEvidence: ["Billboard #13", "Official UK #11"],
        selectionReason:
          "Selected from your owned 1976 releases because its best imported album-chart position is #11. Matches: Billboard #13, Official UK #11. Local Album Score and loved tracks only break chart ties.",
      },
      {
        albumId: "mb:mock-anniversary-3",
        album: "Destroyer",
        artist: "KISS",
        releaseYear: 1976,
        yearsAgo: 50,
        coverPath: mockTimelineCoverUrls[2],
        evidence: "Billboard #11 · Official UK #22 · VG-lista #7 · owned album",
        chartEvidence: ["Billboard #11", "Official UK #22", "VG-lista #7"],
        selectionReason:
          "Selected from your owned 1976 releases because its best imported album-chart position is #7. Matches: Billboard #11, Official UK #22, VG-lista #7. Local Album Score and loved tracks only break chart ties.",
      },
      {
        albumId: "mb:mock-anniversary-4",
        album: "Songs in the Key of Life",
        artist: "Stevie Wonder",
        releaseYear: 1976,
        yearsAgo: 50,
        coverPath: mockTimelineCoverUrls[3],
        evidence: "Billboard #1 · Official UK #2 · VG-lista #4 · owned album",
        chartEvidence: ["Billboard #1", "Official UK #2", "VG-lista #4"],
        selectionReason:
          "Selected from your owned 1976 releases because its best imported album-chart position is #1. Matches: Billboard #1, Official UK #2, VG-lista #4. Local Album Score and loved tracks only break chart ties.",
      },
      {
        albumId: "mb:mock-anniversary-5",
        album: "The Royal Scam",
        artist: "Steely Dan",
        releaseYear: 1976,
        yearsAgo: 50,
        coverPath: mockTimelineCoverUrls[4],
        evidence: "Billboard #15 · Official UK #11 · owned album",
        chartEvidence: ["Billboard #15", "Official UK #11"],
        selectionReason:
          "Selected from your owned 1976 releases because its best imported album-chart position is #11. Matches: Billboard #15, Official UK #11. Local Album Score and loved tracks only break chart ties.",
      },
    ],
    lifeEvents: [
      {
        artistId: "bobby brown",
        artist: "Bobby Brown",
        eventType: "birthday",
        eventDate: "1969-08-11",
        years: 57,
        dayOffset: 0,
        albumCount: 2,
        lovedTracks: 3,
        portraitAvailable: false,
        representativeAlbumId: "mb:mock-life-1",
        representativeAlbum: "Don't Be Cruel",
        representativeCoverPath: mockTimelineCoverUrls[2],
        evidence: "Born today · 2 albums in your library",
      },
      {
        artistId: "john sebastian",
        artist: "John Sebastian",
        eventType: "birthday",
        eventDate: "1944-08-11",
        years: 82,
        dayOffset: 0,
        albumCount: 1,
        lovedTracks: 1,
        portraitAvailable: false,
        representativeAlbumId: "mb:mock-life-2",
        representativeAlbum: "John B. Sebastian",
        representativeCoverPath: mockTimelineCoverUrls[3],
        evidence: "Born today · 1 album in your library",
      },
      {
        artistId: "joe jackson",
        artist: "Joe Jackson",
        eventType: "birthday",
        eventDate: "1954-08-11",
        years: 72,
        dayOffset: 0,
        albumCount: 8,
        lovedTracks: 6,
        portraitAvailable: false,
        representativeAlbumId: "mb:mock-life-4",
        representativeAlbum: "Night and Day",
        representativeCoverPath: mockTimelineCoverUrls[4],
        evidence: "Born today · 8 albums in your library",
      },
      {
        artistId: "eric carmen",
        artist: "Eric Carmen",
        eventType: "birthday",
        eventDate: "1949-08-11",
        years: 77,
        dayOffset: 0,
        albumCount: 5,
        lovedTracks: 3,
        portraitAvailable: false,
        representativeAlbumId: "mb:mock-life-5",
        representativeAlbum: "Eric Carmen",
        representativeCoverPath: mockTimelineCoverUrls[5],
        evidence: "Born today · 5 albums in your library",
      },
      {
        artistId: "richie ramone",
        artist: "Richie Ramone",
        eventType: "birthday",
        eventDate: "1957-08-11",
        years: 69,
        dayOffset: 0,
        albumCount: 3,
        lovedTracks: 2,
        portraitAvailable: false,
        representativeAlbumId: "mb:mock-life-6",
        representativeAlbum: "Entitled",
        representativeCoverPath: mockTimelineCoverUrls[0],
        evidence: "Born today · 3 albums in your library",
      },
      {
        artistId: "robin williams",
        artist: "Robin Williams",
        eventType: "memorial",
        eventDate: "2014-08-11",
        years: 12,
        dayOffset: 0,
        albumCount: 4,
        lovedTracks: 4,
        portraitAvailable: false,
        representativeAlbumId: "mb:mock-memorial-1",
        representativeAlbum: "Live 2002",
        representativeCoverPath: mockTimelineCoverUrls[4],
        evidence: "Remembered today · 4 loved tracks",
      },
      {
        artistId: "jani lane",
        artist: "Jani Lane",
        eventType: "memorial",
        eventDate: "2011-08-11",
        years: 15,
        dayOffset: 0,
        albumCount: 3,
        lovedTracks: 3,
        portraitAvailable: false,
        representativeAlbumId: "mb:mock-memorial-2",
        representativeAlbum: "Back Down to One",
        representativeCoverPath: mockTimelineCoverUrls[3],
        evidence: "Remembered today · 3 loved tracks",
      },
      {
        artistId: "sonny thompson",
        artist: "Sonny Thompson",
        eventType: "memorial",
        eventDate: "1989-08-11",
        years: 37,
        dayOffset: 0,
        albumCount: 2,
        lovedTracks: 2,
        portraitAvailable: false,
        representativeAlbumId: "mb:mock-memorial-3",
        representativeAlbum: "Long Gone",
        representativeCoverPath: mockTimelineCoverUrls[2],
        evidence: "Remembered today · 2 loved tracks",
      },
      {
        artistId: "mike douglas",
        artist: "Mike Douglas",
        eventType: "memorial",
        eventDate: "2006-08-11",
        years: 20,
        dayOffset: 0,
        albumCount: 2,
        lovedTracks: 1,
        portraitAvailable: false,
        representativeAlbumId: "mb:mock-memorial-4",
        representativeAlbum: "The Men in My Little Girl's Life",
        representativeCoverPath: mockTimelineCoverUrls[1],
        evidence: "Remembered today · 1 loved track",
      },
      {
        artistId: "tal farlow",
        artist: "Tal Farlow",
        eventType: "memorial",
        eventDate: "1998-08-11",
        years: 28,
        dayOffset: 0,
        albumCount: 1,
        lovedTracks: 1,
        portraitAvailable: false,
        representativeAlbumId: "mb:mock-memorial-5",
        representativeAlbum: "The Tal Farlow Album",
        representativeCoverPath: mockTimelineCoverUrls[0],
        evidence: "Remembered today · 1 loved track",
      },
    ],
    chartSnapshot: {
      source: "official-uk",
      sourceLabel: "Official UK Albums",
      year: 1986,
      week: 34,
      availableYears: [2005, 1986, 1982],
      availableWeeks: [12, 34, 50],
      stories: [
      {
        entity: "album",
        albumId: "mb:mock-chart-1",
        trackId: null,
        title: "True Blue",
        artist: "Madonna",
        album: "True Blue",
        chart: "Official UK Albums",
        rank: 1,
        chartDate: "1986-08-23",
        chartYear: 1986,
        loved: true,
        coverPath: mockTimelineCoverUrls[1],
        evidence: "#1 on Official UK Albums · owned album",
      },
      {
        entity: "album",
        albumId: "mb:mock-chart-2",
        trackId: null,
        title: "Back in the High Life",
        artist: "Steve Winwood",
        album: "Back in the High Life",
        chart: "Official UK Albums",
        rank: 2,
        chartDate: "1986-08-23",
        chartYear: 1986,
        loved: false,
        coverPath: mockTimelineCoverUrls[2],
        evidence: "#2 on Official UK Albums · owned album",
      },
      {
        entity: "album",
        albumId: "mb:mock-chart-3",
        trackId: null,
        title: "Count Three & Pray",
        artist: "Berlin",
        album: "Count Three & Pray",
        chart: "Official UK Albums",
        rank: 3,
        chartDate: "1986-08-23",
        chartYear: 1986,
        loved: false,
        coverPath: mockTimelineCoverUrls[3],
        evidence: "#3 on Official UK Albums · owned album",
      },
      {
        entity: "album",
        albumId: "mb:mock-chart-4",
        trackId: null,
        title: "Slippery When Wet",
        artist: "Bon Jovi",
        album: "Slippery When Wet",
        chart: "Official UK Albums",
        rank: 4,
        chartDate: "1986-08-23",
        chartYear: 1986,
        loved: false,
        coverPath: mockTimelineCoverUrls[4],
        evidence: "#4 on Official UK Albums · owned album",
      },
      {
        entity: "album",
        albumId: "mb:mock-chart-5",
        trackId: null,
        title: "Solitude/Solitaire",
        artist: "Peter Cetera",
        album: "Solitude/Solitaire",
        chart: "Official UK Albums",
        rank: 5,
        chartDate: "1986-08-23",
        chartYear: 1986,
        loved: false,
        coverPath: mockTimelineCoverUrls[5],
        evidence: "#5 on Official UK Albums · owned album",
      },
      ],
    },
    deepCutSnapshot: {
      year: null,
      decade: null,
      genre: null,
      availableYears: [2013, 2004, 1991, 1984, 1980, 1971],
      availableGenres: [
        { id: "ambient", label: "Ambient" },
        { id: "folk", label: "Folk" },
        { id: "jazz", label: "Jazz" },
        { id: "pop", label: "Pop" },
        { id: "rock", label: "Rock" },
      ],
      matchingAlbumCount: 6,
      stories: [
      {
        trackId: 911,
        title: "Passing Afternoon",
        albumId: "mb:mock-deep-1",
        album: "Our Endless Numbered Days",
        artist: "Iron & Wine",
        trackNumber: 12,
        timeSeconds: 237,
        albumRating: 91,
        releaseYear: 2004,
        genre: "Folk",
        coverPath: mockTimelineCoverUrls[0],
        evidence: "Album rated 91 · track unrated · no imported singles-chart match",
      },
      {
        trackId: 912,
        title: "All My Rowdy Friends",
        albumId: "mb:mock-deep-2",
        album: "Greatest Hits, Vol. 1",
        artist: "Hank Williams Jr.",
        trackNumber: 7,
        timeSeconds: 177,
        albumRating: 90,
        releaseYear: 1971,
        genre: "Rock",
        coverPath: mockTimelineCoverUrls[1],
        evidence: "Album rated 90 · track unrated · no imported singles-chart match",
      },
      {
        trackId: 913,
        title: "When You Were Mine",
        albumId: "mb:mock-deep-3",
        album: "Dirty Mind",
        artist: "Prince",
        trackNumber: 3,
        timeSeconds: 224,
        albumRating: 89,
        releaseYear: 1980,
        genre: "Pop",
        coverPath: mockTimelineCoverUrls[2],
        evidence: "Album rated 89 · track unrated · no imported singles-chart match",
      },
      {
        trackId: 914,
        title: "Wagon",
        albumId: "mb:mock-deep-4",
        album: "Murmur",
        artist: "R.E.M.",
        trackNumber: 9,
        timeSeconds: 249,
        albumRating: 88,
        releaseYear: 1984,
        genre: "Rock",
        coverPath: mockTimelineCoverUrls[3],
        evidence: "Album rated 88 · track unrated · no imported singles-chart match",
      },
      {
        trackId: 915,
        title: "Weightless",
        albumId: "mb:mock-deep-5",
        album: "Ambient 1: Music for Airports",
        artist: "Brian Eno",
        trackNumber: 4,
        timeSeconds: 586,
        albumRating: 93,
        releaseYear: 1991,
        genre: "Ambient",
        coverPath: mockTimelineCoverUrls[4],
        evidence: "Album rated 93 · track unrated · no imported singles-chart match",
      },
      {
        trackId: 916,
        title: "The Sun",
        albumId: "mb:mock-deep-6",
        album: "Journey in Satchidananda",
        artist: "Alice Coltrane",
        trackNumber: 5,
        timeSeconds: 401,
        albumRating: 95,
        releaseYear: 2013,
        genre: "Jazz",
        coverPath: mockTimelineCoverUrls[5],
        evidence: "Album rated 95 · track unrated · no imported singles-chart match",
      },
      ],
    },
    completionSnapshot: {
      mode: "artist",
      year: null,
      decade: null,
      genre: null,
      availableYears: [2024, 2003, 1999, 1988, 1984, 1981, 1977],
      availableGenres: [
        { id: "jazz", label: "Jazz" },
        { id: "pop", label: "Pop" },
        { id: "post-punk", label: "Post-Punk" },
        { id: "rock", label: "Rock" },
        { id: "synthpop", label: "Synthpop" },
      ],
      matchingCount: 6,
      artistStories: [
        {
          artistId: "the cure",
          artist: "The Cure",
          musicbrainzMbid: "mock-cure",
          ownedAlbumCount: 11,
          officialAlbumCount: 14,
          missingAlbumCount: 3,
          completionPercent: 0.79,
          missingReleaseTitle: "Songs of a Lost World",
          missingReleaseYear: 2024,
          genre: "Post-Punk",
          portraitAvailable: false,
          representativeAlbumId: "mb:mock-complete-1",
          representativeAlbum: "Disintegration",
          representativeCoverPath: mockTimelineCoverUrls[0],
          evidence: "11 of 14 official albums owned · 13 local albums",
        },
        {
          artistId: "steely dan",
          artist: "Steely Dan",
          musicbrainzMbid: "mock-steely-dan",
          ownedAlbumCount: 7,
          officialAlbumCount: 9,
          missingAlbumCount: 2,
          completionPercent: 0.78,
          missingReleaseTitle: "Everything Must Go",
          missingReleaseYear: 2003,
          genre: "Rock",
          portraitAvailable: false,
          representativeAlbumId: "mb:mock-complete-2",
          representativeAlbum: "Aja",
          representativeCoverPath: mockTimelineCoverUrls[4],
          evidence: "7 of 9 official albums owned · 8 local albums",
        },
        {
          artistId: "talking heads",
          artist: "Talking Heads",
          musicbrainzMbid: "mock-talking-heads",
          ownedAlbumCount: 7,
          officialAlbumCount: 8,
          missingAlbumCount: 1,
          completionPercent: 0.88,
          missingReleaseTitle: "Naked",
          missingReleaseYear: 1988,
          genre: "Post-Punk",
          portraitAvailable: false,
          representativeAlbumId: "mb:mock-complete-3",
          representativeAlbum: "Remain in Light",
          representativeCoverPath: mockTimelineCoverUrls[5],
          evidence: "7 of 8 official albums owned · 7 local albums",
        },
        {
          artistId: "pet shop boys",
          artist: "Pet Shop Boys",
          musicbrainzMbid: "mock-pet-shop-boys",
          ownedAlbumCount: 12,
          officialAlbumCount: 15,
          missingAlbumCount: 3,
          completionPercent: 0.8,
          missingReleaseTitle: "Please",
          missingReleaseYear: 1986,
          genre: "Synthpop",
          portraitAvailable: false,
          representativeAlbumId: "mb:mock-complete-4",
          representativeAlbum: "Actually",
          representativeCoverPath: mockTimelineCoverUrls[1],
          evidence: "12 of 15 official albums owned · 14 local albums",
        },
        {
          artistId: "joni mitchell",
          artist: "Joni Mitchell",
          musicbrainzMbid: "mock-joni-mitchell",
          ownedAlbumCount: 14,
          officialAlbumCount: 19,
          missingAlbumCount: 5,
          completionPercent: 0.74,
          missingReleaseTitle: "Mingus",
          missingReleaseYear: 1979,
          genre: "Jazz",
          portraitAvailable: false,
          representativeAlbumId: "mb:mock-complete-5",
          representativeAlbum: "Hejira",
          representativeCoverPath: mockTimelineCoverUrls[2],
          evidence: "14 of 19 official albums owned · 16 local albums",
        },
        {
          artistId: "prince",
          artist: "Prince",
          musicbrainzMbid: "mock-prince",
          ownedAlbumCount: 24,
          officialAlbumCount: 28,
          missingAlbumCount: 4,
          completionPercent: 0.86,
          missingReleaseTitle: "Controversy",
          missingReleaseYear: 1981,
          genre: "Pop",
          portraitAvailable: false,
          representativeAlbumId: "mb:mock-complete-6",
          representativeAlbum: "Dirty Mind",
          representativeCoverPath: mockTimelineCoverUrls[3],
          evidence: "24 of 28 official albums owned · 25 local albums",
        },
      ],
      albumStories: [
        {
          albumId: "mb:mock-album-gap-1",
          album: "Actually",
          artist: "Pet Shop Boys",
          releaseYear: 1987,
          genre: "Synthpop",
          totalTracks: 10,
          ratedTracks: 8,
          unratedTracks: 2,
          completionPercent: 0.8,
          coverPath: mockTimelineCoverUrls[0],
          evidence: "8 of 10 tracks rated",
        },
        {
          albumId: "mb:mock-album-gap-2",
          album: "Dirty Mind",
          artist: "Prince",
          releaseYear: 1980,
          genre: "Pop",
          totalTracks: 8,
          ratedTracks: 5,
          unratedTracks: 3,
          completionPercent: 0.625,
          coverPath: mockTimelineCoverUrls[2],
          evidence: "5 of 8 tracks rated",
        },
        {
          albumId: "mb:mock-album-gap-3",
          album: "Remain in Light",
          artist: "Talking Heads",
          releaseYear: 1980,
          genre: "Post-Punk",
          totalTracks: 8,
          ratedTracks: 7,
          unratedTracks: 1,
          completionPercent: 0.875,
          coverPath: mockTimelineCoverUrls[5],
          evidence: "7 of 8 tracks rated",
        },
        {
          albumId: "mb:mock-album-gap-4",
          album: "Mingus",
          artist: "Joni Mitchell",
          releaseYear: 1979,
          genre: "Jazz",
          totalTracks: 6,
          ratedTracks: 3,
          unratedTracks: 3,
          completionPercent: 0.5,
          coverPath: mockTimelineCoverUrls[1],
          evidence: "3 of 6 tracks rated",
        },
        {
          albumId: "mb:mock-album-gap-5",
          album: "The Head on the Door",
          artist: "The Cure",
          releaseYear: 1985,
          genre: "Post-Punk",
          totalTracks: 10,
          ratedTracks: 6,
          unratedTracks: 4,
          completionPercent: 0.6,
          coverPath: mockTimelineCoverUrls[4],
          evidence: "6 of 10 tracks rated",
        },
      ],
    },
    recommendationSnapshot: {
      mode: "played",
      anchors: [
        {
          albumId: "mb:mock-anchor-1",
          album: "Actually",
          artist: "Pet Shop Boys",
          signal: "100% rated recently",
          coverPath: mockTimelineCoverUrls[0],
          evidence: "10 of 10 tracks rated in recent activity",
        },
        {
          albumId: "mb:mock-anchor-2",
          album: "Electric Rendezvous",
          artist: "Al Di Meola",
          signal: "100% rated recently",
          coverPath: mockTimelineCoverUrls[1],
          evidence: "8 of 8 tracks rated in recent activity",
        },
        {
          albumId: "mb:mock-anchor-loved-1",
          album: "Purple Rain",
          artist: "Prince",
          signal: "Album score 418",
          coverPath: mockTimelineCoverUrls[2],
          evidence: "Album score 418 · 4 loved tracks",
        },
        {
          albumId: "mb:mock-anchor-loved-2",
          album: "Hounds of Love",
          artist: "Kate Bush",
          signal: "Album score 312",
          coverPath: mockTimelineCoverUrls[3],
          evidence: "Album score 312 · 3 loved tracks",
        },
      ],
      matchingCount: 24,
      lastfmLinkedCount: 18,
      sonicLinkedCount: 2,
      sonicNote: "2 of 4 anchors have current sound analysis · at least 50% MP3 coverage per album. Refresh as analysis completes.",
      stories: [
        {
          albumId: "mb:mock-because-1",
          album: "Steve McQueen",
          artist: "Prefab Sprout",
          lovedTracks: 0,
          albumScore: null,
          ratedTracks: 0,
          totalTracks: 11,
          ratingCompleteness: 0,
          coverPath: mockTimelineCoverUrls[2],
          reason: "Similar artist",
          sonicDistance: 0.18,
          anchorAlbumId: "mb:mock-anchor-1",
          anchorAlbum: "Actually",
          anchorArtist: "Pet Shop Boys",
          evidence: "Last.fm links Prefab Sprout to Pet Shop Boys · Sounds like Actually by Pet Shop Boys · 8/11 MP3s analyzed · 0% rated",
        },
        {
          albumId: "mb:mock-because-2",
          album: "A Walk Across the Rooftops",
          artist: "The Blue Nile",
          lovedTracks: 0,
          albumScore: null,
          ratedTracks: 2,
          totalTracks: 7,
          ratingCompleteness: 0.286,
          coverPath: mockTimelineCoverUrls[3],
          reason: "Related album",
          sonicDistance: null,
          anchorAlbumId: "mb:mock-anchor-2",
          anchorAlbum: "Electric Rendezvous",
          anchorArtist: "Al Di Meola",
          evidence: "Related to Electric Rendezvous on Last.fm · 29% rated",
        },
        {
          albumId: "mb:mock-because-3",
          album: "Idlewild",
          artist: "Everything But The Girl",
          lovedTracks: 0,
          albumScore: null,
          ratedTracks: 0,
          totalTracks: 12,
          ratingCompleteness: 0,
          coverPath: mockTimelineCoverUrls[4],
          reason: "Similar artist",
          sonicDistance: null,
          anchorAlbumId: "mb:mock-anchor-1",
          anchorAlbum: "Actually",
          anchorArtist: "Pet Shop Boys",
          evidence: "Last.fm links Everything But The Girl to Pet Shop Boys · 0% rated",
        },
        {
          albumId: "mb:mock-because-4",
          album: "Café Bleu",
          artist: "The Style Council",
          lovedTracks: 0,
          albumScore: null,
          ratedTracks: 3,
          totalTracks: 13,
          ratingCompleteness: 0.231,
          coverPath: mockTimelineCoverUrls[5],
          reason: "Shared genre",
          sonicDistance: null,
          anchorAlbumId: "mb:mock-anchor-1",
          anchorAlbum: "Actually",
          anchorArtist: "Pet Shop Boys",
          evidence: "Synthpop link to Actually · 23% rated",
        },
        {
          albumId: "mb:mock-because-5",
          album: "First Light",
          artist: "Pat Metheny Group",
          lovedTracks: 0,
          albumScore: null,
          ratedTracks: 0,
          totalTracks: 9,
          ratingCompleteness: 0,
          coverPath: mockTimelineCoverUrls[1],
          reason: "Similar artist",
          sonicDistance: 0.24,
          anchorAlbumId: "mb:mock-anchor-2",
          anchorAlbum: "Electric Rendezvous",
          anchorArtist: "Al Di Meola",
          evidence: "Sounds like Electric Rendezvous by Al Di Meola · 9/9 MP3s analyzed · 0% rated",
        },
        {
          albumId: "mb:mock-because-6",
          album: "The Dreaming",
          artist: "Kate Bush",
          lovedTracks: 0,
          albumScore: null,
          ratedTracks: 4,
          totalTracks: 10,
          ratingCompleteness: 0.4,
          coverPath: mockTimelineCoverUrls[3],
          reason: "Related album",
          sonicDistance: null,
          anchorAlbumId: "mb:mock-anchor-loved-1",
          anchorAlbum: "Purple Rain",
          anchorArtist: "Prince",
          evidence: "Related to Purple Rain on Last.fm · 40% rated",
        },
      ],
      evidence: "2 recent rating threads · suggestions are under 50% rated",
    },
    listeningEvidenceNote:
      "Listening stories use recent rating activity and loved tracks.",
  },
  heatmap: [
    {
      genreId: "synthpop",
      genre: "Synthpop",
      year: 1987,
      albumCount: 125,
      ratedAlbumCount: 82,
      partialAlbumCount: 21,
      unratedAlbumCount: 22,
      trackCount: 1460,
      lovedTracks: 96,
      averageRatingCompleteness: 0.72,
      averageAlbumScore: 128.4,
    },
    {
      genreId: "post-punk",
      genre: "Post-Punk",
      year: 1986,
      albumCount: 88,
      ratedAlbumCount: 44,
      partialAlbumCount: 19,
      unratedAlbumCount: 25,
      trackCount: 1040,
      lovedTracks: 61,
      averageRatingCompleteness: 0.63,
      averageAlbumScore: 116.9,
    },
    {
      genreId: "heavy metal",
      genre: "Heavy Metal",
      year: 1984,
      albumCount: 76,
      ratedAlbumCount: 18,
      partialAlbumCount: 37,
      unratedAlbumCount: 21,
      trackCount: 812,
      lovedTracks: 34,
      averageRatingCompleteness: 0.41,
      averageAlbumScore: 82.1,
    },
    {
      genreId: "nu-metal",
      genre: "Nu-Metal",
      year: 1999,
      albumCount: 42,
      ratedAlbumCount: 9,
      partialAlbumCount: 21,
      unratedAlbumCount: 12,
      trackCount: 530,
      lovedTracks: 8,
      averageRatingCompleteness: 0.34,
      averageAlbumScore: 61.5,
    },
    {
      genreId: "metalcore",
      genre: "Metalcore",
      year: 2004,
      albumCount: 54,
      ratedAlbumCount: 12,
      partialAlbumCount: 16,
      unratedAlbumCount: 26,
      trackCount: 604,
      lovedTracks: 12,
      averageRatingCompleteness: 0.28,
      averageAlbumScore: 74.8,
    },
    {
      genreId: "video game",
      genre: "Video Game",
      year: 2012,
      albumCount: 64,
      ratedAlbumCount: 50,
      partialAlbumCount: 10,
      unratedAlbumCount: 4,
      trackCount: 1480,
      lovedTracks: 104,
      averageRatingCompleteness: 0.84,
      averageAlbumScore: 151.2,
    },
  ],
  backlogMissions: [
    {
      id: "finish-high-score-partials",
      title: "Finish high-score partials",
      description:
        "Partially rated albums with the strongest Album Score signals.",
      actionLabel: "Open top partials",
      albumCount: 2,
      trackCount: 21,
      lovedTracks: 1,
      averageAlbumScore: 71.8,
      averageRatingCompleteness: 0.39,
      genreId: null,
      genre: null,
      artistId: null,
      artist: null,
      yearFrom: null,
      yearTo: null,
      ratedTracksMin: 1,
      ratingCompletenessMin: null,
      ratingCompletenessMax: 99,
      lovedTracksMin: null,
      sortField: "albumScore",
      sortDirection: "desc",
      limit: 20,
    },
    {
      id: "neglected-decade",
      title: "Rate a neglected decade",
      description:
        "The decade with the largest unfinished album pile. 1980s albums are still open.",
      actionLabel: "Open decade backlog",
      albumCount: 1,
      trackCount: 9,
      lovedTracks: 1,
      averageAlbumScore: 82.1,
      averageRatingCompleteness: 0.44,
      genreId: null,
      genre: null,
      artistId: null,
      artist: null,
      yearFrom: 1980,
      yearTo: 1989,
      ratedTracksMin: null,
      ratingCompletenessMin: null,
      ratingCompletenessMax: 99,
      lovedTracksMin: null,
      sortField: "albumScore",
      sortDirection: "desc",
      limit: 50,
    },
    {
      id: "high-potential-genre",
      title: "High-potential Heavy Metal",
      description:
        "A genre backlog with unusually strong scored-album signals.",
      actionLabel: "Open genre backlog",
      albumCount: 1,
      trackCount: 9,
      lovedTracks: 1,
      averageAlbumScore: 82.1,
      averageRatingCompleteness: 0.44,
      genreId: "heavy metal",
      genre: "Heavy Metal",
      artistId: null,
      artist: null,
      yearFrom: null,
      yearTo: null,
      ratedTracksMin: null,
      ratingCompletenessMin: null,
      ratingCompletenessMax: 99,
      lovedTracksMin: null,
      sortField: "albumScore",
      sortDirection: "desc",
      limit: 40,
    },
  ],
  smartMissions: [
    {
      id: "smart-high-score-partial-decade",
      title: "20 high-score partial albums from the 1980s",
      description: "Best partial-album cluster.",
      actionLabel: "Open partial decade",
      albumCount: 1,
      trackCount: 9,
      lovedTracks: 1,
      averageAlbumScore: 82.1,
      averageRatingCompleteness: 0.44,
      genreId: null,
      genre: null,
      artistId: null,
      artist: null,
      yearFrom: 1980,
      yearTo: 1989,
      ratedTracksMin: 1,
      ratingCompletenessMin: null,
      ratingCompletenessMax: 99,
      lovedTracksMin: null,
      sortField: "albumScore",
      sortDirection: "desc",
      limit: 20,
    },
    {
      id: "smart-loved-incomplete-genre",
      title: "Loved but incomplete Heavy Metal albums",
      description: "A loved-track rich genre that still has unfinished albums.",
      actionLabel: "Open loved genre",
      albumCount: 1,
      trackCount: 9,
      lovedTracks: 1,
      averageAlbumScore: 82.1,
      averageRatingCompleteness: 0.44,
      genreId: "heavy metal",
      genre: "Heavy Metal",
      artistId: null,
      artist: null,
      yearFrom: null,
      yearTo: null,
      ratedTracksMin: null,
      ratingCompletenessMin: null,
      ratingCompletenessMax: 99,
      lovedTracksMin: 1,
      sortField: "lovedTracks",
      sortDirection: "desc",
      limit: 20,
    },
    {
      id: "smart-unrated-high-potential-genre",
      title: "Unrated Metalcore waiting room",
      description:
        "A fully unrated genre pocket whose rated neighbors score well.",
      actionLabel: "Open unrated genre",
      albumCount: 1,
      trackCount: 10,
      lovedTracks: 0,
      averageAlbumScore: 74.8,
      averageRatingCompleteness: 0.28,
      genreId: "metalcore",
      genre: "Metalcore",
      artistId: null,
      artist: null,
      yearFrom: null,
      yearTo: null,
      ratedTracksMin: null,
      ratingCompletenessMin: null,
      ratingCompletenessMax: 0,
      lovedTracksMin: null,
      sortField: "year",
      sortDirection: "desc",
      limit: 30,
    },
  ],
  loveRatingPoints: [
    {
      albumId: "mb:mock-score",
      album: "Journey",
      albumArtistDisplay: "Austin Wintory",
      genreId: "video game",
      genre: "Video Game",
      year: 2012,
      lovedTracks: 3,
      albumScore: 251.16,
      effectiveAlbumRating: 91,
      ratingCompleteness: 1,
      totalSeconds: 3480,
    },
    {
      albumId: "mb:mock-1",
      album: "Actually",
      albumArtistDisplay: "Pet Shop Boys",
      genreId: "synthpop",
      genre: "Synthpop",
      year: 1987,
      lovedTracks: 2,
      albumScore: 207.62,
      effectiveAlbumRating: 86,
      ratingCompleteness: 1,
      totalSeconds: 2880,
    },
    {
      albumId: "mb:mock-metal",
      album: "Holy Diver",
      albumArtistDisplay: "Dio",
      genreId: "heavy metal",
      genre: "Heavy Metal",
      year: 1984,
      lovedTracks: 1,
      albumScore: 82.1,
      effectiveAlbumRating: 74,
      ratingCompleteness: 0.44,
      totalSeconds: 2520,
    },
  ],
  genrePoints: [
    {
      genreId: "synthpop",
      genre: "Synthpop",
      albumCount: 1840,
      trackCount: 21_440,
      lovedTracks: 720,
      totalSeconds: 4_102_000,
      partialAlbumCount: 230,
      unratedAlbumCount: 928,
      averageRatingCompleteness: 0.49,
      averageAlbumScore: 128.42,
    },
    {
      genreId: "post-punk",
      genre: "Post-Punk",
      albumCount: 1390,
      trackCount: 15_890,
      lovedTracks: 488,
      totalSeconds: 3_006_000,
      partialAlbumCount: 211,
      unratedAlbumCount: 671,
      averageRatingCompleteness: 0.52,
      averageAlbumScore: 119.08,
    },
    {
      genreId: "heavy metal",
      genre: "Heavy Metal",
      albumCount: 1320,
      trackCount: 14_820,
      lovedTracks: 350,
      totalSeconds: 3_230_000,
      partialAlbumCount: 196,
      unratedAlbumCount: 712,
      averageRatingCompleteness: 0.37,
      averageAlbumScore: 101.68,
    },
    {
      genreId: "video game",
      genre: "Video Game",
      albumCount: 820,
      trackCount: 18_200,
      lovedTracks: 640,
      totalSeconds: 4_560_000,
      partialAlbumCount: 112,
      unratedAlbumCount: 204,
      averageRatingCompleteness: 0.71,
      averageAlbumScore: 151.2,
    },
  ],
  artistPoints: [
    {
      artistId: "pet shop boys",
      artist: "Pet Shop Boys",
      albumCount: 24,
      trackCount: 260,
      lovedTracks: 46,
      totalSeconds: 72_000,
      partialAlbumCount: 3,
      unratedAlbumCount: 6,
      averageRatingCompleteness: 0.74,
      averageAlbumScore: 135.2,
      topGenre: "Synthpop",
    },
    {
      artistId: "the smiths",
      artist: "The Smiths",
      albumCount: 12,
      trackCount: 118,
      lovedTracks: 26,
      totalSeconds: 34_000,
      partialAlbumCount: 2,
      unratedAlbumCount: 4,
      averageRatingCompleteness: 0.66,
      averageAlbumScore: 118.6,
      topGenre: "Post-Punk",
    },
    {
      artistId: "dio",
      artist: "Dio",
      albumCount: 9,
      trackCount: 92,
      lovedTracks: 12,
      totalSeconds: 28_400,
      partialAlbumCount: 4,
      unratedAlbumCount: 2,
      averageRatingCompleteness: 0.44,
      averageAlbumScore: 82.1,
      topGenre: "Heavy Metal",
    },
  ],
  generatedAt: "2026-06-25T09:03:20Z",
};
