import type { MusicToolProgress, MusicBrainzArtistDiscographyResponse, MusicBrainzArtistInfoImportProgress, MusicBrainzArtistInfoPreview, MusicBrainzArtistInfoPreviewRow, MusicBrainzArtistInfoStatus, MusicBrainzCacheStatus, MusicBrainzOriginCountryImportProgress, MusicBrainzOriginCountryPreview, MusicBrainzOriginCountryPreviewRow, MusicBrainzOriginCountryStatus } from "../../types";
import { defaultMusicBrainzCachePath } from "../normalization";

export const mockMusicBrainzCacheStatus: MusicBrainzCacheStatus = {
  cachePath: defaultMusicBrainzCachePath,
  resolvedPath: `Preview runtime / ${defaultMusicBrainzCachePath}`,
  exists: true,
  valid: true,
  state: "warning",
  message: "Preview cache is readable, with artist mapping warnings to review.",
  fileSizeBytes: 152_092_672,
  artistCount: 20_208,
  distinctMbidCount: 18_552,
  duplicateMbidCount: 1_656,
  suspiciousMappingCount: 1_656,
  releaseGroupCount: 483_675,
  officialReleaseGroupCount: 483_675,
  pureAlbumReleaseGroupCount: 188_420,
  releaseYearMin: 1889,
  releaseYearMax: 2026,
  cacheDateMin: "2026-02-07 20:09:01",
  cacheDateMax: "2026-02-11 14:47:32",
  warningExamples: [
    {
      mbid: "preview-shared-mbid",
      cachedNameCount: 4,
      releaseGroupCount: 242,
      cachedNames: [
        "canonical artist",
        "alternate spelling",
        "featured credit",
        "search mismatch",
      ],
    },
  ],
};

export const mockMusicBrainzOriginRun = {
  id: 1,
  scope: "album-artists",
  status: "completed",
  totalArtists: 6,
  eligibleCount: 4,
  fetchedCount: 4,
  skippedCount: 1,
  unresolvedCount: 1,
  failedCount: 0,
  lastProcessedArtistKey: "dio",
  startedAt: "2026-07-07T09:15:00.000Z",
  completedAt: "2026-07-07T09:15:05.000Z",
  errorSummary: null,
};

export const mockMusicBrainzOriginCountryStatus: MusicBrainzOriginCountryStatus = {
  totalAlbumArtists: 6,
  importedOrigins: 5,
  countryCount: 3,
  manualOrigins: 1,
  unresolvedOrigins: 1,
  missingOrigins: 1,
  lastRun: mockMusicBrainzOriginRun,
  countries: [
    { code: "AE", name: "AE", artistCount: 1 },
    { code: "GB", name: "United Kingdom", artistCount: 2 },
    { code: "US", name: "United States", artistCount: 2 },
  ],
};

export const mockMusicBrainzArtistInfoRun = {
  id: 1,
  scope: "album-artists",
  status: "completed",
  totalArtists: 6,
  eligibleCount: 4,
  fetchedCount: 4,
  skippedCount: 1,
  unresolvedCount: 0,
  failedCount: 0,
  lastProcessedArtistKey: "madonna",
  startedAt: "2026-07-08T10:12:00.000Z",
  completedAt: "2026-07-08T10:12:05.000Z",
  errorSummary: null,
};

export const mockMusicBrainzArtistInfoStatus: MusicBrainzArtistInfoStatus = {
  totalAlbumArtists: 6,
  importedInfos: 4,
  personArtists: 2,
  groupArtists: 2,
  genderedArtists: 2,
  bornArtists: 2,
  diedArtists: 1,
  foundedArtists: 2,
  dissolvedArtists: 1,
  missingInfos: 2,
  lastRun: mockMusicBrainzArtistInfoRun,
};

export const mockMusicBrainzOriginPreviewRows = [
  {
    localArtistKey: "pet shop boys",
    displayArtist: "Pet Shop Boys",
    albumCount: 1,
    musicbrainzMbid: "012151a8-preview-psb",
    matchedName: "pet shop boys",
    matchMethod: "verified-link",
    artistLinkState: "verified",
    suspectMapping: false,
    existingCountryCode: "GB",
    existingCountryName: "United Kingdom",
    existingReviewState: "imported",
    status: "alreadyImported",
    skippedReason: null,
  },
  {
    localArtistKey: "the smiths",
    displayArtist: "The Smiths",
    albumCount: 1,
    musicbrainzMbid: "preview-smiths",
    matchedName: "the smiths",
    matchMethod: "manual-mbid",
    artistLinkState: "verified",
    suspectMapping: false,
    existingCountryCode: "GB",
    existingCountryName: "United Kingdom",
    existingReviewState: "reviewed",
    status: "manual",
    skippedReason: null,
  },
  {
    localArtistKey: "austin wintory",
    displayArtist: "Austin Wintory",
    albumCount: 1,
    musicbrainzMbid: "preview-austin-wintory",
    matchedName: "Austin Wintory",
    matchMethod: "exact-name",
    artistLinkState: "unverified",
    suspectMapping: false,
    existingCountryCode: null,
    existingCountryName: null,
    existingReviewState: null,
    status: "eligible",
    skippedReason: null,
  },
  {
    localArtistKey: "dio",
    displayArtist: "Dio",
    albumCount: 1,
    musicbrainzMbid: "preview-dio",
    matchedName: "Dio",
    matchMethod: "exact-name",
    artistLinkState: "unverified",
    suspectMapping: false,
    existingCountryCode: "US",
    existingCountryName: "United States",
    existingReviewState: "imported",
    status: "eligible",
    skippedReason: null,
  },
  {
    localArtistKey: "korn",
    displayArtist: "Korn",
    albumCount: 1,
    musicbrainzMbid: "preview-shared-mbid",
    matchedName: "Korn",
    matchMethod: "exact-name",
    artistLinkState: "unverified",
    suspectMapping: true,
    existingCountryCode: null,
    existingCountryName: null,
    existingReviewState: null,
    status: "skipped",
    skippedReason: "Skipped suspect or duplicate-heavy cache mapping.",
  },
  {
    localArtistKey: "killswitch engage",
    displayArtist: "Killswitch Engage",
    albumCount: 1,
    musicbrainzMbid: null,
    matchedName: null,
    matchMethod: "none",
    artistLinkState: "none",
    suspectMapping: false,
    existingCountryCode: null,
    existingCountryName: null,
    existingReviewState: null,
    status: "unresolved",
    skippedReason: "No high-confidence MusicBrainz artist match.",
  },
] satisfies MusicBrainzOriginCountryPreview["rows"];

export const mockMusicBrainzArtistInfoPreviewRows = [
  {
    localArtistKey: "david bowie",
    displayArtist: "David Bowie",
    albumCount: 4,
    musicbrainzMbid: "5441c29d-3602-4898-b1a1-b77fa23b8e50",
    matchedName: "David Bowie",
    matchMethod: "verified-link",
    artistLinkState: "verified",
    suspectMapping: false,
    existingSortName: "Bowie, David",
    existingArtistType: "Person",
    existingGender: "Male",
    existingBeginDate: "1947-01-08",
    existingBeginYear: 1947,
    existingEndDate: "2016-01-10",
    existingEndYear: 2016,
    existingEnded: true,
    existingBeginAreaName: "Brixton, Lambeth, London",
    existingEndAreaName: "New York, New York",
    existingReviewState: "imported",
    status: "alreadyImported",
    skippedReason: null,
  },
  {
    localArtistKey: "the chordettes",
    displayArtist: "The Chordettes",
    albumCount: 2,
    musicbrainzMbid: "mock-chordettes-mbid",
    matchedName: "The Chordettes",
    matchMethod: "exact-name",
    artistLinkState: "unverified",
    suspectMapping: false,
    existingSortName: "Chordettes, The",
    existingArtistType: "Group",
    existingGender: null,
    existingBeginDate: "1946",
    existingBeginYear: 1946,
    existingEndDate: "1963",
    existingEndYear: 1963,
    existingEnded: true,
    existingBeginAreaName: "Sheboygan, Wisconsin",
    existingEndAreaName: "Sheboygan, Wisconsin",
    existingReviewState: "imported",
    status: "alreadyImported",
    skippedReason: null,
  },
  {
    localArtistKey: "def leppard",
    displayArtist: "Def Leppard",
    albumCount: 3,
    musicbrainzMbid: "8f92558c-2baa-4758-8c38-615519e9deda",
    matchedName: "Def Leppard",
    matchMethod: "manual-mbid",
    artistLinkState: "verified",
    suspectMapping: false,
    existingSortName: "Def Leppard",
    existingArtistType: "Group",
    existingGender: null,
    existingBeginDate: "1977",
    existingBeginYear: 1977,
    existingEndDate: null,
    existingEndYear: null,
    existingEnded: false,
    existingBeginAreaName: "Sheffield, South Yorkshire, England",
    existingEndAreaName: null,
    existingReviewState: "imported",
    status: "alreadyImported",
    skippedReason: null,
  },
  {
    localArtistKey: "madonna",
    displayArtist: "Madonna",
    albumCount: 5,
    musicbrainzMbid: "79239441-bfd5-4981-a70c-55c3f15c1287",
    matchedName: "Madonna",
    matchMethod: "verified-link",
    artistLinkState: "verified",
    suspectMapping: false,
    existingSortName: "Madonna",
    existingArtistType: "Person",
    existingGender: "Female",
    existingBeginDate: "1958-08-16",
    existingBeginYear: 1958,
    existingEndDate: null,
    existingEndYear: null,
    existingEnded: false,
    existingBeginAreaName: "Bay City, Michigan",
    existingEndAreaName: null,
    existingReviewState: "imported",
    status: "alreadyImported",
    skippedReason: null,
  },
  {
    localArtistKey: "austin wintory",
    displayArtist: "Austin Wintory",
    albumCount: 1,
    musicbrainzMbid: "preview-austin-wintory",
    matchedName: "Austin Wintory",
    matchMethod: "exact-name",
    artistLinkState: "unverified",
    suspectMapping: false,
    existingSortName: null,
    existingArtistType: null,
    existingGender: null,
    existingBeginDate: null,
    existingBeginYear: null,
    existingEndDate: null,
    existingEndYear: null,
    existingEnded: null,
    existingBeginAreaName: null,
    existingEndAreaName: null,
    existingReviewState: null,
    status: "eligible",
    skippedReason: null,
  },
  {
    localArtistKey: "killswitch engage",
    displayArtist: "Killswitch Engage",
    albumCount: 1,
    musicbrainzMbid: null,
    matchedName: null,
    matchMethod: "none",
    artistLinkState: "none",
    suspectMapping: false,
    existingSortName: null,
    existingArtistType: null,
    existingGender: null,
    existingBeginDate: null,
    existingBeginYear: null,
    existingEndDate: null,
    existingEndYear: null,
    existingEnded: null,
    existingBeginAreaName: null,
    existingEndAreaName: null,
    existingReviewState: null,
    status: "unresolved",
    skippedReason: "No high-confidence MusicBrainz artist match.",
  },
] satisfies MusicBrainzArtistInfoPreview["rows"];

export const mockOriginProgressHandlers = new Set<
  (progress: MusicBrainzOriginCountryImportProgress) => void
>();

export const mockMusicToolProgressHandlers = new Set<
  (progress: MusicToolProgress) => void
>();

export function emitMockMusicToolProgress(progress: MusicToolProgress) {
  for (const handler of mockMusicToolProgressHandlers) {
    handler(progress);
  }
}

export function emitMockMusicBrainzOriginProgress(
  progress: MusicBrainzOriginCountryImportProgress,
) {
  for (const handler of mockOriginProgressHandlers) {
    handler(progress);
  }
}

export const mockArtistInfoProgressHandlers = new Set<
  (progress: MusicBrainzArtistInfoImportProgress) => void
>();

export function emitMockMusicBrainzArtistInfoProgress(
  progress: MusicBrainzArtistInfoImportProgress,
) {
  for (const handler of mockArtistInfoProgressHandlers) {
    handler(progress);
  }
}

export function mockOriginProgress(
  status: string,
  totalArtists: number,
  eligibleCount: number,
  processedCount: number,
  fetchedCount: number,
  storedCount: number,
  skippedCount: number,
  unresolvedCount: number,
  failedCount: number,
  row: MusicBrainzOriginCountryPreviewRow | null,
  message: string,
): MusicBrainzOriginCountryImportProgress {
  const remainingCount = Math.max(0, eligibleCount - processedCount);
  const percent =
    eligibleCount > 0
      ? Math.min(100, Math.max(0, (processedCount / eligibleCount) * 100))
      : 0;
  return {
    status,
    totalArtists,
    eligibleCount,
    processedCount,
    remainingCount,
    fetchedCount,
    storedCount,
    skippedCount,
    unresolvedCount,
    failedCount,
    percent,
    currentArtist: row?.displayArtist ?? null,
    currentArtistKey: row?.localArtistKey ?? null,
    currentMbid: row?.musicbrainzMbid ?? null,
    message,
  };
}

export function mockArtistInfoProgress(
  status: string,
  totalArtists: number,
  eligibleCount: number,
  processedCount: number,
  fetchedCount: number,
  storedCount: number,
  skippedCount: number,
  unresolvedCount: number,
  failedCount: number,
  row: MusicBrainzArtistInfoPreviewRow | null,
  message: string,
): MusicBrainzArtistInfoImportProgress {
  const remainingCount = Math.max(0, eligibleCount - processedCount);
  const percent =
    eligibleCount > 0
      ? Math.min(100, Math.max(0, (processedCount / eligibleCount) * 100))
      : 0;
  return {
    status,
    totalArtists,
    eligibleCount,
    processedCount,
    remainingCount,
    fetchedCount,
    storedCount,
    skippedCount,
    unresolvedCount,
    failedCount,
    percent,
    currentArtist: row?.displayArtist ?? null,
    currentArtistKey: row?.localArtistKey ?? null,
    currentMbid: row?.musicbrainzMbid ?? null,
    message,
  };
}

export const mockMusicBrainzDiscographies: Record<
  string,
  MusicBrainzArtistDiscographyResponse
> = {
  "pet shop boys": {
    artistKey: "pet shop boys",
    artistName: "Pet Shop Boys",
    state: "available",
    message:
      "Matched 3 pure official MusicBrainz albums against 1 local album.",
    cachePath: defaultMusicBrainzCachePath,
    resolvedPath: `Preview runtime / ${defaultMusicBrainzCachePath}`,
    musicbrainzMbid: "012151a8-preview-psb",
    matchedCacheName: "pet shop boys",
    matchMethod: "exact-name",
    artistLinkState: "unverified",
    artistLinkIgnored: false,
    suspectMapping: false,
    cachedNameCount: 1,
    totalReleaseGroupCount: 3,
    pureAlbumCount: 3,
    ownedCount: 1,
    missingCount: 2,
    excludedCount: 0,
    localAlbumCount: 1,
    completion: 1 / 3,
    releaseGroupSource: "cache",
    releaseGroupUpdatedAt: null,
    candidates: [],
    releases: [
      {
        releaseMbid: "preview-please",
        title: "Please",
        year: 1986,
        trackCount: 11,
        status: "missing",
        localAlbumId: null,
        localAlbumTitle: null,
        localYear: null,
        matchMethod: "none",
        confidence: 0,
        decision: null,
      },
      {
        releaseMbid: "preview-actually",
        title: "Actually",
        year: 1987,
        trackCount: 10,
        status: "owned",
        localAlbumId: "mb:mock-1",
        localAlbumTitle: "Actually",
        localYear: 1987,
        matchMethod: "normalized-title-year",
        confidence: 1,
        decision: null,
      },
      {
        releaseMbid: "preview-behaviour",
        title: "Behaviour",
        year: 1990,
        trackCount: 10,
        status: "missing",
        localAlbumId: null,
        localAlbumTitle: null,
        localYear: null,
        matchMethod: "none",
        confidence: 0,
        decision: null,
      },
    ],
  },
  "the smiths": {
    artistKey: "the smiths",
    artistName: "The Smiths",
    state: "warning",
    message:
      "Matched through the preview cache, but this artist has alternate cached names. Review before trusting broad reports.",
    cachePath: defaultMusicBrainzCachePath,
    resolvedPath: `Preview runtime / ${defaultMusicBrainzCachePath}`,
    musicbrainzMbid: "preview-smiths",
    matchedCacheName: "the smiths",
    matchMethod: "exact-name",
    artistLinkState: "unverified",
    artistLinkIgnored: false,
    suspectMapping: true,
    cachedNameCount: 2,
    totalReleaseGroupCount: 2,
    pureAlbumCount: 2,
    ownedCount: 1,
    missingCount: 1,
    excludedCount: 0,
    localAlbumCount: 1,
    completion: 0.5,
    releaseGroupSource: "cache",
    releaseGroupUpdatedAt: null,
    candidates: [
      {
        name: "The Smiths",
        mbid: "preview-smiths",
        matchMethod: "same-mbid-name",
        score: 0.98,
        cachedNameCount: 2,
        totalReleaseGroupCount: 2,
        suspectMapping: true,
      },
    ],
    releases: [
      {
        releaseMbid: "preview-queen-is-dead",
        title: "The Queen Is Dead",
        year: 1986,
        trackCount: 10,
        status: "owned",
        localAlbumId: "mb:mock-2",
        localAlbumTitle: "The Queen Is Dead",
        localYear: 1986,
        matchMethod: "normalized-title-year",
        confidence: 1,
        decision: null,
      },
      {
        releaseMbid: "preview-strangeways",
        title: "Strangeways, Here We Come",
        year: 1987,
        trackCount: 10,
        status: "missing",
        localAlbumId: null,
        localAlbumTitle: null,
        localYear: null,
        matchMethod: "none",
        confidence: 0,
        decision: null,
      },
    ],
  },
};
